### ISSUE TITLE
Problem with Esc key in 3642

### ISSUE THREAD

**Issue by ppipp** [FAForever/fa#786] opened 2015-07-19 07:44 UTC
Since the patch, several people (including Visionik) complained about Esc key not functioning anymore, or not the same way it used to. 
Examples:
http://forums.faforever.com/forums/viewtopic.php?f=2&t=10307&start=10
http://forums.faforever.com/forums/viewtopic.php?f=3&t=10281

**Comment by Sheeo** [comment] 2015-07-19 19:14
883e499f8eb9ad1b182d5d0f3941b1b0df7f0b09 may or may not fix this issue, I've marked it as fixed since the escapehandler stack can no longer become invalid, and we don't have any steps to reproduce this.

Please try and reproduce on the `release/3643` branch.

**Closed** 2015-07-19 19:49 UTC
Labels: bug, high, ui
