### ISSUE TITLE
ASF hitting Carriers

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#1901] opened 2017-04-08 11:29 UTC
You can still attack Carriers with air units as long as you have a target that is about to dock on the carrier.

**Comment by aeoncleanse** [comment] 2017-04-08 12:31
The bullets should definitely be able to impact, but if once it docks the asf drop target, its working as intended

**Comment by PhilipJFryFAF** [comment] 2017-04-09 17:10
they do not lose target that is the issue

**Comment by MrRowey** [comment] 2022-06-12 22:58
Closing issues for now Balance Team Can Re Open if they intend to fix

**Closed by MrRowey** 2022-06-12 22:58 UTC
Labels: type: bug, area: balance, area: sim, priority: low
