### ISSUE TITLE
[Beta] Ping issue

### ISSUE THREAD

**Issue by hugst** [FAForever/fa#1603] opened 2016-10-12 14:59 UTC
In the beta, the other team see your team pings, and your team dont see them.
Same for billy nuke ...
If someone in your team shoot a nuke or a billy , the other team will have the graphic animation and the sound but not your team.

**Comment by aeoncleanse** [comment] 2016-10-12 15:02
I just tested this with LICKI. Could not reproduce.

**Comment by hugst** [comment] 2016-10-12 15:36
You can go in replay ID : 5264506
Start watching about min 17 Keyser got billy. Put you in Clinch view, and you will see Clinch have the ping and animation of the billy that keyser is sending on him.

For the classic ping, we clearly understund the bug during 2nd game, we had player on both team on the same ts. On first game we just complain that ping didnt work, and someone realise on the other team that he was seeing my ping when neither me or any of my teamate was seeing them

**Comment by Crotalus** [comment] 2016-10-22 14:35
AFAIK this is fixed in latest beta

**Closed by Crotalus** 2016-10-22 14:35 UTC
Labels: bug, regression
