### ISSUE TITLE
Score screen shows both players as loss

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1250] opened 2016-05-04 00:25 UTC
Could be the cause of the rating troubles.

**Comment by Exotic-Retard** [comment] 2016-05-04 00:36
there was an old issue that sometimes showed precisely 0 info, saying statistics could not be displayed. it was from before this patch. cant reproduce, but when it did happen it happened for all players in the game afaik.

dunno how useful this is but hope this helps

**Comment by HUSSAR-mtrela** [comment] 2016-05-04 04:10
I think this is a duplicate of issue #1229

**Comment by aeoncleanse** [comment] 2016-05-04 21:48
Related but not the same, this doesn't require a draw. It just shows both as a loss even when one clearly won. However, I can't reproduce offline...

**Closed** 2016-09-20 01:16 UTC
