### ISSUE TITLE
ACU able to move during upgrades - non-beta

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1015] opened 2015-11-08 22:41 UTC
http://forums.faforever.com/forums/viewtopic.php?f=2&t=11089&p=113751#p113751

**Comment by HUSSAR-mtrela** [comment] 2015-12-15 21:26
I have verified that this issue is already fixed in 3652 release and it was related to issue #1048 which was fixed by me and @Crotalus

**Comment by HUSSAR-mtrela** [comment] 2015-12-15 21:27
someone else should confirm it and close this issue

**Comment by zlo-faf** [comment] 2015-12-16 06:55
So it should be fixed in beta now already? I can test it later today

**Comment by Sheeo** [comment] 2015-12-17 02:48
@zlo-faf yes, if it's fixed in the release branch it should be live in the beta now.

**Comment by zlo-faf** [comment] 2015-12-17 19:17
If fix exists, it is not in beta yet
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=4193776

**Comment by HUSSAR-mtrela** [comment] 2015-12-18 05:51
I will investigate this issue. Thanks @zlo-faf for the replay.

**Comment by HUSSAR-mtrela** [comment] 2015-12-18 21:08
@zlo-faf, I saw this issue in your replay but I cannot reproduce it in the latest beta. I even removed all my mods, and gave ACU move - upgrade - move commands very fast but that did not trigger this issue. Can someone else try to reproduce this issue in FAF beta?

**Comment by zlo-faf** [comment] 2015-12-20 17:18
@HUSSAR-mtrela, looks like FAF beta was just updated, and now this issue is fixed (at least i can't do it anymore) makes me happy and sad at the same time

**Comment by HUSSAR-mtrela** [comment] 2016-03-05 00:37
@Sheeo can you close this issue?

**Closed** 2016-03-05 03:49 UTC
