### ISSUE TITLE
Transport not targetable by AA when stationary

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#1670] opened 2016-11-07 00:14 UTC
[5384309-JaggedAppliance.zip](https://github.com/FAForever/fa/files/574233/5384309-JaggedAppliance.zip)
Zlo makes a ghetto and when it is stationary on the right of the map you can see the aa can't shoot the trans and so the labs just kill the aa.

**Comment by aeoncleanse** [comment] 2016-11-07 01:56
I suspect anything offmap can't be targeted...

**Comment by JaggedAppliance** [comment] 2016-11-07 15:05
There was no offmapping ...

**Comment by aeoncleanse** [comment] 2016-11-07 15:25
Ohhhhh... Was it simply landed?

**Comment by Exotic-Retard** [comment] 2016-11-07 18:00
air unit are able to shoot at landed air units, regardless of what they do.
however aa units cant do that, so it would explain why.
also the trans landing height is a little dubious so its not very obvious.

i kinda think this is a non-issue tbh

**Comment by aeoncleanse** [comment] 2016-11-07 18:13
If that's what happened here, I agree.

**Comment by zlo-faf** [comment] 2016-11-07 18:48
https://youtu.be/mIpx9mwG1sA?t=4m39s
transport "landed" despite floating quite hight in the air
also afaik it used to be impossible to land transport with units, currently it seems to be changed
i have not tested it but from replay you can see that ground based aa was not able to shoot landed transport, while tanks were able to shoot it.

**Comment by aeoncleanse** [comment] 2016-11-07 19:21
Landing with units has always been a thing.

**Comment by JaggedAppliance** [comment] 2016-11-08 20:08
What happens in this game if you would watch it is the ghetto stops and the labs inside kill the aa which can do nothing vs the trans despite it hovering way up in the air.

**Comment by aeoncleanse** [comment] 2016-11-08 20:43
OK finally got time to watch it and... I have no idea. It looks like the transport thought it was in the landed state. My GUESS is it tried to land and something went under it, aborting the land physically, but not the code which tells it what layer it's on... Very strange.

**Comment by Exotic-Retard** [comment] 2016-11-13 11:03
no nothing special here, it simply landed. transports with units have a much higher hover height when on the ground. labs can shoot from trans regardless of what layer its on. as i said before, it hovers so high it doesnt look like its on the ground. you know it is because you can target it with ground units. on that replay to check this you simply select some of jaggeds auroras or sth and mouse over the trans. in fact, he did have an aurora shoot the trans while it was there a couple of times

i would close this issue but i feel like that would be a bit rude

**Comment by JaggedAppliance** [comment] 2016-11-17 17:56
I think either labs should not shoot out of the trans when it's in this "landed" state or AAs should be able to shoot at them when they are "landed." Or both. In the replay you can see what can happen, trans is being chased by AAs and it can just "land" and kill the AAs without being shot.

**Comment by Exotic-Retard** [comment] 2016-11-17 18:42
either or both is pretty easy to do. however i dont find any of this concerning that much. if i can be convinced i would make the aas shoot landed air units - simply make them able to shoot ground (and water) as well then restrict targets to only air categories, just like all air units currently have.

**Comment by Exotic-Retard** [comment] 2016-11-17 18:43
but i think this is not so bad. you can hide the transport from aas like this, and its not much different to landing and dropping the labs.

i think what got you there is that it didnt look landed. thats all. so it looks op but its not really.

**Comment by aeoncleanse** [comment] 2016-12-21 19:10
We can have the transport disable contained weapons when layer changes to LAND.

**Comment by aeoncleanse** [comment] 2017-01-01 21:14
Exotic and I have confirmed 100% that transports which are idle, whether empty (Low to ground, bit more obvious) or filled with units (Hover a bit higher), the engine counts them as being on the Land layer,

**Closed** 2017-02-07 23:07 UTC
