### ISSUE TITLE
Air scout infinite intel bug

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#848] opened 2015-08-07 09:34 UTC
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=3728134

First scout from blue player got shot down off map and was giving infinite intel on opponent's base.

**Comment by ChrisKitching** [comment] 2015-08-11 00:55
Sheeo and I watched the replay: the scout provided intel for 20s after crashing as expected, then it went away.

Not a bug.

**Comment by Varaxis** [comment] 2015-08-11 01:32
I've encountered this bug before, able to reproduce it, but somewhat unreliably, by sending massive amounts of sera t1 scouts to get shot down by a variety of AA emplacements.

**Comment by speed2CZ** [comment] 2015-08-11 02:49
I watched the replay and radar coverage on that base from dead scout was there for more than 10 minutes

**Comment by ChrisKitching** [comment] 2015-08-11 11:27
Ah, the radar. Wish you'd said that before, I was checking out the VizMarker.

**Comment by speed2CZ** [comment] 2015-08-11 13:26
well that's what I said, Intel, not vision :P you just think too fast

**Comment by Sheeo** [comment] 2015-08-11 13:42
Vision, UnderwaterVision, Radar and Omni are all 'intel'.

**Comment by speed2CZ** [comment] 2015-08-11 13:47
you forgot Sonar, but whatever :P

**Comment by Sheeo** [comment] 2015-08-11 13:49
Indeed :)

**Comment by duk3luk3** [comment] 2015-08-16 08:19
Happened to me in a ladder game the other day on flooded tabula. Infinite radar over opponent's base.

**Comment by Sheeo** [comment] 2015-08-17 01:28
@duk3luk3 can you provide the replay id?

**Comment by duk3luk3** [comment] 2015-08-17 18:54
replay.faforever.com/3760775

**Comment by duk3luk3** [comment] 2017-02-22 18:37
Could this be fixed by making maps bigger but restricting the playable size?

**Comment by aeoncleanse** [comment] 2017-02-22 18:54
I have a fix in mind if we confirm this ia the cause

**Closed** 2017-05-11 21:58 UTC
Labels: bug, sim
