### ISSUE TITLE
PROBLEM: Useless ground turrets because of landscape

### ISSUE THREAD

**Issue by MerryPanda** [FAForever/fa#3068] opened 2020-04-10 19:17 UTC
Maps can have unnoticeable height variations that make ground turrets nearly useless. I think it harms the game, but I can't propose a solution besides making them higher... or grand them missiles or "plasma blobs" that are able to bypass hills and depressions...

What can we do? :D

**Comment by jediflamaster** [comment] 2020-04-10 20:33
Using the terrain to get around turrets is a lot of fun. The problem is game doesn't communicate where the turret will be effectively shooting before you build it, so it may be crap for the builder because they had no way of checking the turret's effective range before commiting the mass. UI gizmo that shows guaranteed turret range (as in the area where the turret is guaranteed a line of sight to its target) would likely be best, but IDK if FA would allow that and it would be prohibitively expensive to implement for more than 1 unit at a time.

**Comment by RecklessCharger** [comment] 2020-09-27 19:54
You need to know the map or hold space and zoom in and have a look at the terrain before you build PD (easier said than done I know)

**Comment by MrRowey** [comment] 2021-11-08 00:35
@Garanas this can be closed as it has nothing to do with the game more to do with maps variations

**Closed** 2021-11-08 06:28 UTC
