### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION at address 0x0095854f

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#1445] opened 2016-08-27 13:29 UTC
This error shows up several times. (possibility: 32Bit memory full)

25 Jul 2013:
http://forums.faforever.com/viewtopic.php?f=26&t=4555
20 Jan 2015
http://forums.faforever.com/viewtopic.php?p=90768#p91716
10 Oct 2015:
http://forums.faforever.com/viewtopic.php?f=31&t=10938
23 Oct 2015:
http://forums.faforever.com/viewtopic.php?f=31&t=11003
17 Jan 2016
http://pastebin.com/iZ6wBQQR
27 Aug 2016:
http://forums.faforever.com/viewtopic.php?f=3&t=13011
29 Sep 2016
http://forums.faforever.com/viewtopic.php?f=3&t=13208
01.Nov 2016
http://forums.faforever.com/viewtopic.php?f=2&t=13399#p138167
05 Jan 2017
http://forums.faforever.com/viewtopic.php?f=79&t=13776
21.Mar 2017
http://forums.faforever.com/viewtopic.php?f=3&t=14158#p145712
29.Jul 2017
http://forums.faforever.com/viewtopic.php?f=15&t=14930
02.Feb 2018
Reported from discord user
02.Oct.2018
https://github.com/FAForever/fa/issues/1445#issuecomment-426048893
02.Dec.2018
https://github.com/FAForever/fa/issues/1445#issuecomment-443334222
02.Sep.2019
https://forums.faforever.com/viewtopic.php?f=3&t=18065
03.Jan.2020
http://forums.faforever.com/viewtopic.php?f=3&t=18575
24.Apr.2021
https://forum.faforever.com/topic/1533

Hints from user:
`while watching a replay that causes this error:
the crash occures about 10 min earlier than yesterday ingame`

`I get this crash if idle engie mod is enabled`

`Reducing fidelity settings eliminates it`

**Comment by speed2CZ** [comment] 2016-11-01 09:59
Happened to CookieNoob in the new coop mission at 1h mark
http://forums.faforever.com/viewtopic.php?f=2&t=13399#p138167

**Comment by CookieNoob** [comment] 2016-11-05 12:23
happened again... (same mission, differnent time)
[game.txt](https://github.com/FAForever/fa/files/573158/game.txt)
[debugwindow.txt](https://github.com/FAForever/fa/files/573159/debugwindow.txt)

**Comment by speed2CZ** [comment] 2016-11-15 20:26
Tokyto always crashes in Novax Station Assault, +-10min after getting into second part of the mission
https://gist.github.com/speed2CZ/1ec9ed69ff5450b9ce277d2b36006c22

**Comment by speed2CZ** [comment] 2017-01-05 11:02
And another one http://forums.faforever.com/viewtopic.php?f=79&t=13776

**Comment by Ellesedil** [comment] 2017-01-27 08:00
I'm the player in question for the above crash, and I just had this happen a second time.

https://forums.faforever.com/viewtopic.php?f=79&t=13776&p=142637#p142637

Both instances occurred while playing on a large map as Aeon. Not sure if either of those things are a trend or not, but I thought I'd mention them.

**Comment by Exotic-Retard** [comment] 2017-01-27 11:28
it shouldnt be related to the mod i guess, we dont change sounds in it

**Comment by PhilipJFryFAF** [comment] 2018-02-01 17:00
log from a discord user
```EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0095854f
    attempted to write memory at 0x037e0000

Callstack:
    Unknown symbol (address 0x0095854f)(edited)```

[j4RbZ3Ey.txt](https://github.com/FAForever/fa/files/1686427/j4RbZ3Ey.txt)

**Comment by Uveso** [comment] 2018-02-02 13:05
i viewed the log and the last line was:
```
Game.prefs(1): invalid control char near `char(0)'
```
I guess the old game.pref file from the user is not available ?

**Comment by Eonfge** [comment] 2018-10-01 20:21
Can confirm that this issue is still a thing.

### Base info
Ubuntu 18.04 LTS
Nvidia 396.54
Wine 1.13

### Reporting data
[0x0095854f_log.txt](https://github.com/FAForever/fa/files/2435436/0x0095854f_log.txt)
[0x0095854f_hardinfo_report.txt](https://github.com/FAForever/fa/files/2435437/0x0095854f_hardinfo_report.txt)

### Replay
[8632123-Eonfge.zip](https://github.com/FAForever/fa/files/2435449/8632123-Eonfge.zip)

**Comment by Uveso** [comment] 2018-10-02 14:45
Thanks for reporting this.

Your log shows many of these errors:
`warning: Error running lua script: ..lua\sim\unit.lua(5105): attempt to call field `IsInCombat' (a nil value)
`
But 'IsInCombat' is not a main game variable.
This is from a modded unit.lua file.
Please check what mod is causing this error.

**Comment by SpheroidDev** [comment] 2018-10-02 20:43
Same issue.

```
 EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0095854f
    attempted to write memory at 0x028d1980
```

Crash each time after 30-40 minutes on Dual Gap map.
It starts a couple weeks ago with no specific software or hardware changes/updates.

I did reinstall all FAF/SC software with total cleanup. I tried to change system sound configuration several times and some other tips wich mentioned on FAF forum. Still nothing helps.

[sc_crash_report_2018_10_02_spheroid.txt](https://github.com/FAForever/fa/files/2439615/sc_crash_report_2018_10_02_spheroid.txt)

[brief_system_info_2018_10_02_spheroid.txt](https://github.com/FAForever/fa/files/2439614/brief_system_info_2018_10_02_spheroid.txt)
[replay-8636154-Spheroid.zip](https://github.com/FAForever/fa/files/2439638/replay-8636154-Spheroid.zip)

**Comment by Eonfge** [comment] 2018-10-03 19:57
@Uveso That would be the TvG experience mod, the one that causes all units to upgrade like crazy for some very interesting games.

I had it today again, but I sadly hit escape before I could copy the log to somewhere save. After that, the game log didn't actually feature the crash info I needed. Was the same 54f though.

Had waves of these errors before, but not sure what triggered them. Longer games and modded games seem more fragile, but nothing really unique to isolate.

**Comment by Eonfge** [comment] 2018-10-15 19:37
Here a log of a crash without mods or anything. 

Was a 6 vs 6 on Duel Gap, a proper campy nuka-fest.

[0x0095854f_log.txt](https://github.com/FAForever/fa/files/2480262/0x0095854f_log.txt)

**Comment by SpheroidDev** [comment] 2018-11-06 11:44
No one crash since patch 3701 (2018-10-29). Looks like problem just disappeared (no HW/SW changes on host machine).

**Comment by Eonfge** [comment] 2018-11-30 20:46
Must disappoint you @SpheroidDev:

```
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0095854f
    attempted to write memory at 0x01f60000

Program : Z:\home\kevin\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /mean 1085.87 /deviation 103.809 /country /init init_faf.lua /numgames 377 /log /home/kevin/FAForever/logs/game.uid.8908710.log /nobugreport /savereplay gpgnet://localhost:32777/8908710/Eonfge.SCFAreplay /gpgnet 127.0.0.1:41859
```

**Comment by Eonfge** [comment] 2018-12-12 20:55
[0x0095854f_log.txt](https://github.com/FAForever/fa/files/2673488/0x0095854f_log.txt)

This one has some more interesting stuff in it. Something about a CWldSession::DoBeat() missing an entity

**Comment by Uveso** [comment] 2018-12-13 09:32
`info: CWldSession::DoBeat() unknown entity id (0x2ff0077a) supplied in a pose update.`
This only means we have a unit that is destroyed and still present as c-object.
Not a crash reason :/

**Comment by Uveso** [comment] 2018-12-13 09:55
@SpheroidDev 

I tested your mod to get the error, but got no error.
How long should i run the mod ? Or how long are you running the mod until it makes errors ?

<0x0095854f> Spawned: 15668 (15668):
![spam](https://user-images.githubusercontent.com/17804547/49930516-0f175580-fec5-11e8-9b8b-0fb0bc1e4134.png)

**Comment by SpheroidDev** [comment] 2018-12-14 16:44
@Uveso
This dirty brute force method takes (for me) about 3-4 minutes to get crash.
There a fresh one:
![0x0095854f-mod-crash-screenshot-2018-12-14](https://user-images.githubusercontent.com/43795009/50013532-6f47ed80-ffd2-11e8-9fb0-69ede3d3739a.png)

Yes, there is a 2GB limit for 32-bit processes and so on. And getting crash in this way it is not the same as crash during correct gameplay. But. But.
You may see that crash (for example this fresh one) is about access memory at 0x028f0000 address. That is in "Low 2GB (0x00000000 through 0x7FFFFFFF) - Used by the process" memory range. It looks like there is a bug in some memory allocation/management code of ForgedAlliance.exe. Some "incorrect signed/unsigned integer offset/indexing" kind of bug. And if this bug leads to crash in this synthetic "over 2GB" case, then the same bug may cause crash in more natural execution flow.

This crash is not an issue for me since patch 3701 and I have not found other (than mod) method to reproduce this crash. So, for now, I have stop try to debug out bug more precisely.

**Comment by Uveso** [comment] 2018-12-14 23:07
Yeah it's fine. 
At least we know something more about the bug.
Better then guessing; It's maybe a "sound" bug. :)

**Comment by Eonfge** [comment] 2018-12-15 08:14
> @Uveso
> This crash is not an issue for me since patch 3701 and I have not found other (than mod) method to reproduce this crash. So, for now, I have stop try to debug out bug more precisely.

Uhm, my reproduction case of two days ago was with 3701, without mods or anything. Was a 6 v 6 Double Gap game, so that might have something to do with it.

Should I try running the mod and look for anomalies?

**Comment by SpheroidDev** [comment] 2018-12-16 13:32
@Eonfge 
Unfortunately, reproducing this crash again and again with mod will not give us more information about this bug. I can't now imagine what anomalies you may look out if you'll try using mod. So, I don't think that you should waste your time for this. But thanks.

**Comment by Garanas** [comment] 2022-07-31 18:22
Closing this issue - I haven't seen it and if it pops up again we can use the official debugger available in the client:

![image](https://user-images.githubusercontent.com/15778155/182040024-03ce6a69-685c-4606-bcde-c234ae8b0501.png)

Besides that, lets use #2045 to track this in the future.

**Closed by Garanas** 2022-07-31 18:22 UTC
Labels: type: core dump
