### ISSUE TITLE
SML and SMD slow build when stalling

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#711] opened 2015-06-29 18:47 UTC
This bug has been around for too long and since this patch is bug fixing, I think this could use some attention.

If you're loading nuke or antinuke and stalling mass, it basically stops (takes forever to load). Easy to reproduce. Get SMD, some mass income, stall a bit and it stops loading.

**Comment by aeoncleanse** [comment] 2015-06-30 12:00
Took another look at this, still cannot find where it's happening. Must be engine :(

**Comment by duk3luk3** [comment] 2015-06-30 12:39
How much does it really stall? It should use resources proportional to the total deployed build power. Can you clearly show that it doesn't?

**Comment by aeoncleanse** [comment] 2015-06-30 12:48
just try it. have nothing else draining.

**Comment by duk3luk3** [comment] 2015-06-30 13:03
https://dl.dropboxusercontent.com/u/2808338/smd-stall-test.SCFAReplay

+14 Mass, stalling all the way: SMD builds in 4:37 minutes
+16 Mass, so not stalling: SMD builds in exactly 4 Minutes

14/15 == 0.93 so stalling SMD can only be using 93% of its build power so should take 1.07 times longer than non-stalling SMD, therefore 240 seconds (4 Minutes) * 1.07 = 257 Seconds = 4:17 so SMD takes 20 seconds longer to load than it should according to my guesstimation which is 20/240 = 8.3% too long.

That is not "it stops loading" by a large margin.

**Comment by aeoncleanse** [comment] 2015-06-30 13:16
Cool. Looks like this isn't a problem really then, just observer error. Shouldn't it be 14/16?

**Comment by duk3luk3** [comment] 2015-06-30 13:16
No, SMD mass consumption is 15, but I had +15 mass.

**Comment by aeoncleanse** [comment] 2015-06-30 13:28
OK so... 4 minutes is the intended time. It takes 4:37 to build when it is denied 1 mass per second compared to what it wants. That means it's being given 240/277 = 0.8664 times the amount compared to normal stall. As in, if it takes that much longer, only this much mass is actually making it into the unit/buildpower is being used.

Next, we need to find out the completion times with -2, -3, -4 mass. That should allow us to get more numbers, see if there's a pattern.

**Comment by aeoncleanse** [comment] 2015-06-30 14:42
OK so once and for all we can put this to bed. There is no bug to be found with Missile building speeds in any normal situation.

So, here's the data and the process: 

SMD Missile costs 3600 Mass, and in normal circumstances builds in exactly 240s. We tested how long it took to build that same missile, denying it one mass per second at each stage. The SMD requests 15 mass per second.

X = Mass income per second.

Theoretical completion time = 240s * (100 * (X / 15))

Therefore:

15 should be 240s, actually 240s
14 should be 257s, tested at 256s (Accounted for by some mass making it into storage in between builds)
13 should be 277s, tested at 277s
12 should be 300s, tested at 300s
11 should be 327s, tested at 325s

Importantly, if you have NO storage whatsoever available, then we DO begin to see massive increases in build-time, and wasted resources. However, this is a situation which should never, ever be seen outside of Supremacy, which is a rarely played game mode. It can only arise with no Storages and no ACU. 

As long as you have Storage available, from our ingame testing, the actual completion times correspond to the theoretical.

**Comment by speed2CZ** [comment] 2015-06-30 15:36
400 mass income, trying to use 500, that means 100 mass stall, SMD needed OVER 20 MINUTES to load, and you can see that the loading bar was jumping ahead only when I didnt mass stall (engies moving to another task) so dont tell me there isnt anything wrong.

Those are numbers from average late game of air player.

replay ID: 3594970

**Comment by duk3luk3** [comment] 2015-06-30 17:25
Okay so what appears to be happening in speed2's replay is indeed that the SMD appears to be turned off completely.

Here's how I get to that:

A GC takes 27500 mass to build with 20625 build time. An aeon t3 engy has bp 40. (27500 / 20625) * 40 = 53.3 then gives us the mass/s the engy should be consuming. This times 10 for 10 engies gives 533.3 mass. The summed mass expenditure display says 534. So unless we assume the display is off by 15 due to rounding errors, it is completely omitting the SMD.

**Comment by quark036** [comment] 2015-06-30 17:28
The bug might be that the smd's loading rate is proportional to how much mass you are stalling, rather than just proportional to how much mass you are taking in (ie, it's not getting its share of mass)

**Comment by quark036** [comment] 2015-06-30 17:29
But that's hypothetical

**Comment by tenconamei** [comment] 2015-06-30 17:32
The discrepancy couldn't be due to rounding discrepancies; the maximum rounding error from 10 engineers would be ~9.9 mass, and there's 15 mass expenditure unaccounted for.

**Comment by duk3luk3** [comment] 2015-06-30 17:38
It is definitely not getting its share of mass, we've established that by now.

(If it was getting its share of mass, it should be building at at least 75% the normal speed, i.e. should take only 1.3 times as long as normal, which is 312 seconds)

**Comment by aeoncleanse** [comment] 2015-06-30 17:46
Resources are shared relative to the mass/buildpower ratio between all subjects. GC assisted is 500 mass/200bp or so,  smd is 15 mass/1000 bp.  Therefore the amount it gets is miniscule in comparison. Try changing smd buildpower and missile buildtime to a lower amount,  still same rate,  and you'll see this situation dissolve

**Comment by quark036** [comment] 2015-06-30 17:48
But that would make it possible to spam an smd very quickly with lots of bp

**Comment by aeoncleanse** [comment] 2015-06-30 17:51
Not so,  as to double the working bp on the missile would need you to add 1000 bp.  This is why assisting sml/smd build barely makes a difference.

**Comment by duk3luk3** [comment] 2015-06-30 17:51
@aeoncleanse Could you go into more detail as to how resources are allocated? Is that in the Lua code somewhere?

**Comment by quark036** [comment] 2015-06-30 17:53
Right, but then we are back at the original problem that it completely
stops when you stall mass.

**Comment by duk3luk3** [comment] 2015-06-30 18:05
SMD bp is 1080, antinuke build time is 259200 (in ticks? that's what's in the bp file).

so you're saying that if I divide both by ten, that would remove the problem?

Interestingly the projectiles aren't modded in FAF.

**Comment by aeoncleanse** [comment] 2015-06-30 18:05
Its all handled in engine.  Look,  its very simple,  we have a choice: We have SMD etc unable to be effectively assisted,  OR we have them not stall out if you have other,  very high drain projects going

**Comment by aeoncleanse** [comment] 2015-06-30 18:06
Yes,  I believe I if you divided by 10 or,  hell,  50, this problem would be reduced

**Comment by quark036** [comment] 2015-06-30 18:11
So who decides which choice we make?

**Comment by duk3luk3** [comment] 2015-06-30 18:18
Divided by 10, can't observe better behaviour with regards to SMD stall.... https://dl.dropboxusercontent.com/u/2808338/smd-stall-test-2.SCFAReplay

**Comment by ChrisKitching** [comment] 2015-06-30 19:17
Couldn't we increase the build time for the missile, and increase the build power of the launcher by the same amount? That way the native code would perhaps allocate a better share?

**Comment by duk3luk3** [comment] 2015-06-30 19:18
According to @aeoncleanse it should be working exactly the other way around.

**Comment by aeoncleanse** [comment] 2015-06-30 19:19
Yjp,  increasing both will make the issue worse,  I believe

**Comment by duk3luk3** [comment] 2015-06-30 19:30
Neither increasing nor decreasing SMD buildpower and Missile buildtime makes any difference in my test. https://dl.dropboxusercontent.com/u/2808338/smd-stall-test-4.SCFAReplay

**Comment by aeoncleanse** [comment] 2015-06-30 22:07
Well, back to the drawing board then. Either way, it appears we can do nothing about this, whatever's causing it.

**Comment by duk3luk3** [comment] 2015-07-01 07:27
How does the engine determine which buildings to classify as "turn off when stalling"? It must be possible to find a work-around for that.

**Comment by aeoncleanse** [comment] 2015-07-01 09:27
It would likely be the Categories list in the unit bp. Try removing whatever unique value IDs them as SML/SMD

**Comment by aeoncleanse** [comment] 2015-07-01 15:41
Do TML have this issue?

**Comment by duk3luk3** [comment] 2015-07-01 16:53
removing ANTIMISSILE trait does absolutely nothing (It doesn't appear to really do anything on buildings engine-wise), removing the SILO trait makes it not build missiles so that's a dead end.

**Comment by speed2CZ** [comment] 2015-07-01 17:45
afaik all missiles are affected, strategic and tactical

**Comment by aeoncleanse** [comment] 2015-07-01 18:06
OK so apparently none of these things, when you toggle the missile build on/off, call any of OnWorkBegin, UpdateConsumptionValues, or OnStartBuild... Which is REALLY odd!

**Comment by quark036** [comment] 2015-07-01 19:39
So at this point, tml, sml, and smd basically just work by magic :D

**Comment by quark036** [comment] 2015-07-01 20:13
So, I'm thinking its probably hardcoded, and is activated by the SILO trait, because that is common to SMD, SML, and TML. Off to go do some testing.

**Comment by quark036** [comment] 2015-07-01 20:40
Ok, I added the SILO trait to a t3 pgen, and then did the test with +400 and -500 mass income and expenditure, but did NOT see the same problem, so, back to the drawing board

**Comment by aeoncleanse** [comment] 2015-07-01 21:59
That's because T3 PGens don't consume resources, nor are they able to build missiles. IssueSiloBuildNuke and IssueSiloBuildTactical are engine commands used to put the units into this state. I no longer think it's to do with the SILO Category, it's any unit where one of those two functions is in operation.

**Comment by duk3luk3** [comment] 2015-07-03 06:01
Can we fake the engine out by turning the missile buildings into things that just produce garrisoned units (like aircraft carriers do) that we use as dummies and then just spawning the missile projectiles into them when the dummy production is finished?

**Comment by quark036** [comment] 2015-07-04 05:17
Before we do that, we should decide if we want to change this behavior at all, given the trade off between assisting being ineffective and it sucking up all your resources.

**Comment by quark036** [comment] 2015-07-24 18:59
@Zockyzock?

**Comment by Zockyzock** [comment] 2015-07-25 10:55
I don't understand the relation, if this fixes the bug, it's great (but as i understand its nothing more than a vague hope), and you can still have the missile with high BT and launcher with high BP so you can't assist. 

Any solution that can't keep the nukes being hard to assist would be bad.

**Comment by quark036** [comment] 2015-07-25 13:40
The issue is that if we do that, nukes and anti will get a huge percent of your resources because those are usually allocated relative to that projects percent of your total bp

**Comment by duk3luk3** [comment] 2015-07-25 14:10
If we're going to create some kind of work-around that "cheats" anyway we can also do something to keep nukes being hard to assist.

We could also implement the work-around - given that we find one - for defense (SMD) only. That would shift balance slightly by making it more micro-intensive to rush a nuke (and TMLs).

**Comment by quark036** [comment] 2015-07-25 14:13
I mean yeah, we can keep them being hard to assist, but as far as I understand it, the engine adds up all your bp, then divides your available resources according to the proportion of bp used on each project. If the sml and and don't have this slow build when stalling, due to their huge bp, they would take up most of your resources whether you wanted them to or not

**Comment by CookieNoob** [comment] 2017-05-22 12:03
I think its quite strange that no one mentioned here how the missile building actually works (and this is also the reason why it behaves so strangely during a stall).

When a missile is build, its construction is split into pieces (its easier to see when stalling power instead of mass). For each "segment" of the construction of a nuke, it requires 4000 power. This amount is the one that is requested from the silo. Lets assume the owner of the nuke has an income of +10 power and the nuke is the only entity that requests power. That means that at the second tick, the same "block" is still under construction, but the nuke now requests 3990 power instead of 4000 (10 power are already paid). This continues until the nuke charges the last 10 power to finish the segment of the missile and starts a new segment (it will drain 4000 power again and the whole thing starts over).

Lets assume we have multiple consumers now:
we have a nuke that drains 4k power and a constant drain of 4k power for another unit which is build with the same buildpower as the nuke buildpower and a total power income of 10.
At the first tick the nuke and second unit both request 4k power and are created with equal buildpower so their share of the available power is the same (5 power each). At the second tick, the nuke only requests 3995 power, while the other unit drains 4k still. The portion of the nuke on the total power requirement reduces as each segment of the missile is constructed. The amount of power that the nuke actually receives is getting less during the charge-up for the following reason:
Lets assume we reached the time when the nuke will require 5 power to finish the first block. This leads to a total power requirement of 4005. The interesting part is now, how the available 10 power are split between the two consumers. The player stalls power at 10/4005 which is ~0.25%. All entities with the same buildpower are slowed by the same factor which in turn mean that the nuke will only receive 0.25% of the required 5 power. At the next tick it requires 4.99 power and thus receives even less. Therefore the missile construction is basically stopped when the current segment of the missile is almost finished and the power or mass requirements are not matched.

Assisting engies are not affected by this as their drain is not adjusted to the actual requirements for the current segment. This means that an engy will be slowed down properly (by the correct percentage).

This is fixable creating the nukes similar to carriers (as already suggested) and increasing the silo count when the proxy unit is finished.

**Comment by aeoncleanse** [comment] 2017-05-22 12:25
I haven't looked into how Carriers do it, but I don't _think_ they use a proxy unit... 

Also, reason nobody mentioned it is because nobody knew. I sure didn't. This explanation makes quite a lot of sense in explaining why they get resources differently to other things though.

Why are the chunks 4000 E, and where is this defined?

**Comment by CookieNoob** [comment] 2017-05-22 14:05
well it's indirectly defined via the missile blueprint:
https://github.com/FAForever/fa/blob/287276db8ef4db691da8f54ba477e77583666695/projectiles/AIFQuantumWarhead03/AIFQuantumWarhead03_proj.bp#L44

energy cost / buildtime * buildrate = 1350000 / 324000 * 1080 = 4500

yea I know I said 4k, I wrote it from my memory :)

**Comment by CookieNoob** [comment] 2017-05-22 14:06
well it's indirectly defined via the missile blueprint:
https://github.com/FAForever/fa/blob/287276db8ef4db691da8f54ba477e77583666695/projectiles/AIFQuantumWarhead03/AIFQuantumWarhead03_proj.bp#L44

energy cost / buildtime * buildrate = 1350000 / 324000 * 1080 = 4500

yea I know I said 4k, I wrote it from my memory :)

You can easily test it by just spawning a nuke and only having the acu as power source. Just look at the eco panel.

**Comment by aeoncleanse** [comment] 2017-05-22 15:29
Still, nice catch mate

**Comment by Exotic-Retard** [comment] 2017-05-22 18:44
nice writeup indeed. i noticed this behaviour but never really thought about it tbh xD

also i was under the impression that carriers build directly, just like any other factory unit.

i believe that what cookienoob wrote applies to everything that isnt a unit, more specifically im referring to CreateEconomyEvent which is for example used by the uef acu to rebuild drones. we can see the same behaviour with it while stalling there

**Comment by zlo-faf** [comment] 2018-03-02 14:24
> also i had considered the proxy unit solution already - its feasible but contains a few potential issues - the silo would need to be able to assist/build that unit which means it needs the command cap enabled which may be abused to build other things. potentially. or repair them. this could be solved with scripts but needs to be not forgotten

Carriers used to do all of those things, also unit or building that they assisted was loading into the carrier  after that  witch was hillarious. But currently carriers got fixed and no longer do all of those things. we should make it that way and test it.  I wish that we fix this problem already...

**Comment by Exotic-Retard** [comment] 2018-03-03 09:23
actually, now that kyryl and maclay are here, there is a chance that we could fix this problem properly. what should happen is that silos should not be requesting decreasing amounts of resources, and instead request the full "block" every time, and refund anything that they get too much of. this way, they should stall proportionately to the mass stall and everything should be fine.

another interesting point is engy assistance. i havent gone and tested this but im pretty sure they arent affected when assisting nukes, and work properly as expected.

**Comment by Garanas** [comment] 2021-09-08 11:27
As far as I know this issue is still there - but I personally consider it a feature and part of balance. @Tagada14 , is this the intended idea of launchers (SMD, SML, ...) (e.g., they don't work if you stall) or has this been an issue that is hard to fix should deserve more attention in the future?

If it is the intended idea of launchers in general then you can close this issue.

**Comment by zlo-faf** [comment] 2021-09-09 07:44
I find it can theoretically be a good feature for TML, so TML does not stall you so hard when you make to much of it.
However it still means that you CAN'T make missiles while stalling even if you want to, you need to go and micromanage stuff to stop stalling.
SMD not building missiles while stall is a big noob-trap
And another problem with this feature is that it is not described anywhere

**Comment by Garanas** [comment] 2021-09-09 08:35
I agree that it is a trap for beginners and that should be addressed in some manner.

**Comment by Garanas** [comment] 2021-09-12 22:07
What if we add a decal below the SMD when it stalls? Some kind of error decal?

**Comment by Tagada14** [comment] 2021-09-14 13:48
I've asked the rest of the balance team but in my opinion, this would be a nice fix.

**Comment by Garanas** [comment] 2021-09-14 14:25
The decal that I proposed?

**Comment by Tagada14** [comment] 2021-09-14 14:36
No, fixing the logic of the missile building so that it behaves like the rest of the units.

**Comment by zlo-faf** [comment] 2021-09-16 14:28
> What if we add a decal below the SMD when it stalls? Some kind of error decal?

i don't see enought reasons to keep this mechanic in game... Noob trap with SMDs is just so big. It is easy to forget about even by experienced players. (even tho i think right now with nuke rushes on GAP, pretty much everyone should already know about this...)
If we remove this mechanic and then it is kinda obvious why everything is slow to build when you are stalling.
Right now if someone asks why SMD is slow to build when you are stalling you can say that all missiles do that "just because"... what if person asks "how much slower does it get build?" we can only answer "it is complicated"

oh... this reminded me... i thick capture and refuel also uses this mechanic. Capturing and refuiling (repairing air unit on the air staging) also drasticly slows down when you are stalling... not 100% sure it uses exactly same mechanic but can maybe check in 1-2 weeks time xD (tho i think nobody cares about capture and air-staging-repair)

**Comment by Garanas** [comment] 2021-09-16 17:48
The problem with fixing it is that it may be quite a hard fix to get right 😄

**Comment by ChessBerry** [comment] 2022-02-20 21:19
Soo, after some strange games yesterday, I learned of this quirks existence and have a simple question: Did smd/nuke loading behavior get changed since the 2015 discussion above? 

In [this test game](https://replay.faforever.com/16406971) I have an income of 169 and a drain of about 200 (actually fluctuating between 182-222 due to the weird smd/nuke mass cost ticks), so I'm stalling about 25% mass. 

Naively I'd assume my smd/nuke to load 25% slower. It gets slowed down by more than that though, much more. In the above test game, the smd doesn't need 4 or 5, but 30 minutes, _half an hour_, to load which seems a bit excessive for a 25% stall.

In the 2015 discussion above they are talking about percentages of "8.3% too long." and not 600% slower, which is what I have found in the test game.

What's going on here?

**Comment by Garanas** [comment] 2022-02-20 21:24
Make one SMD and have sufficient mass, but not sufficient power. The missile is chopped into smaller and smaller pieces. I'm not sure why - it is engine related. Behavior has not changed as far as I am aware.

**Comment by ChessBerry** [comment] 2022-02-20 21:42
@Garanas Yeah I read the past discussion about the weird behavior. What surprised me is the magnitude of slowdown: 
An smd that takes half on hour to load when you stall 25% mass (with lots of energy) may as well not exist at all, which is much different from the "this missile loads 10% slower than it should" framing that the 2015 discussion seemingly had.

**Comment by Garanas** [comment] 2022-07-31 15:03
At this point I consider this to be a feature instead of a bug. The bottom line is: don't stall when you have SMDs. The best we can do is add some kind of indicator that the SMD is not producing at a full capacity - suggestions are welcome, but lets discuss that on Discord.

**Closed by Garanas** 2022-07-31 15:03 UTC
Labels: area: engine, type: enhancement, area: sim

**Comment by lL1l1** [comment] 2025-02-16 02:43
Fixed by https://github.com/FAForever/FA-Binary-Patches/pull/92.
