### ISSUE TITLE
obs in game

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2141] opened 2017-08-08 11:43 UTC
is it possible to create a new way to treat observer ?
the issue we have is that if we enable observer, to let some person spectate a game, the players that will die, will also see the whole map.
it would be nice to separate the 2 features.
Make one that allow observer in game, but doesn't allow player to see whole map after death.
Make one that allow player to see the whole map after death.

**Comment by MrNukealizer** [comment] 2017-08-08 18:02
I don't think that will work. It would be possible to not automatically make someone an observer when they die, but if observers are enabled they could still type `SetFocusArmy -1` in the console to see everything.

**Comment by CookieNoob** [comment] 2017-08-17 13:06
duplicate of #1752

**Comment by duk3luk3** [comment] 2017-08-17 13:08
> but if observers are enabled they could still type `SetFocusArmy -1` in the console to see everything.

And we couldn't detect that and kick them out?

**Comment by CookieNoob** [comment] 2017-08-17 13:15
maybe we can just remove the console function `SetFocusArmy( )` for this lobby option?

**Comment by MrNukealizer** [comment] 2017-08-17 19:00
You can't really remove the console function because any UI mod could bring it back. Now that I think of it, it would be possible to add something to the sim function that's called when someone changes focus that would kick them if they started as a player but changed to -1.

**Comment by CookieNoob** [comment] 2017-08-17 21:10
we could just fork a thread from the acu "OnKilled" function which is attached to the AIBrain of the player and checks every second if GetFocusArmy is still -1

**Comment by MrNukealizer** [comment] 2017-08-17 22:25
There's no need to check the focus army every second. `/schook/lua/SimSync.lua` has the function `NoteFocusArmyChanged` which is called when it changes.

**Closed** 2020-03-30 18:10 UTC
Labels: type: nice-to-have
