### ISSUE TITLE
Connection messages are logged twice

### ISSUE THREAD

**Issue by micheljung** [FAForever/fa#1623] opened 2016-10-23 23:15 UTC
```
Connection to ..... established.
Connection to ..... established.

Lost connection to ....
Lost connection to ....
```

**Comment by aeoncleanse** [comment] 2016-10-24 01:24
Wonder when this started...

**Comment by aeoncleanse** [comment] 2017-01-27 17:28
The latter is called in lobbyComm.DataReceived = function(self,data), so it could be multiple messages being sent that's the cause. The former is in function SetSlotInfo(slotNum, playerInfo).

**Comment by aeoncleanse** [comment] 2017-01-27 17:35
OK I did a test with Voodoo, Jackherer, and Jitsu. The "Connection to _ established" message only appeared once. The "Lost connection to _" message appeared only once for me when Voodoo was asked to DC (I was host), but it appeared twice for each other player.

**Comment by Garanas** [comment] 2022-08-01 15:47
This is trashing the logs, but it is not a critical issue. Closing as not planned.

**Closed by Garanas** 2022-08-01 15:47 UTC
Labels: type: bug, status: need review, priority: low
