### ISSUE TITLE
Error with T3 Loyalist stuns

### ISSUE THREAD

**Issue by PerfectWay** [FAForever/fa#1778] opened 2017-01-16 19:24 UTC
Destruction T3 Cybran bots Loyalist puts stun on air units. Tested on T3 bombers and scouts.

**Comment by Exotic-Retard** [comment] 2017-01-16 20:25
duplicate bug report; fixed in https://github.com/FAForever/fa/pull/1764

**Comment by Exotic-Retard** [comment] 2017-01-16 21:38
apparently the issue is still present in current develop version, dunno whats up with that tbh.

**Comment by aeoncleanse** [comment] 2017-01-16 22:05
Dunno if it's IN develop. FAFdevelop?

**Comment by PerfectWay** [comment] 2017-01-16 22:15
All current version (FAF, FAF beta & FAF develop) has this issue

**Comment by aeoncleanse** [comment] 2017-01-21 19:12
Right. As of present, it should only be in fafbeta. It is. It works.

**Closed** 2017-01-21 19:15 UTC
