### ISSUE TITLE
can't repair CZAR or assist it building unit

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2731] opened 2019-02-24 23:41 UTC
Atlantis and Fatboy can be assist; but you can't assist the CZAR.

The CZAR is the only unit in the game that can't be repaired (also sat, but it isn't purposed to take damage)

**Comment by speed2CZ** [comment] 2019-07-14 08:23
Well it's not completelly true.
![ForgedAlliance_2019-07-14_10-20-10](https://user-images.githubusercontent.com/10947024/61181065-249e5a80-a621-11e9-946b-072a9cab2eef.png)
The problem is gonna be the elevation. Even the ACUs can't always assist, if they are under the CZAR, because they can't aim the build arm at the czar.

The same probably happens to the engineers.

**Comment by HUSSAR-mtrela** [comment] 2019-12-24 21:52
potential fixes:
- add a script/toggle to land a Czar in similar way subs can dive/surface
- add flying engineers with elevation close to Czar flying elevation
- add repair-at-distance function to staging platform that can repair Czar when hovering over staging
- some other way?

**Comment by zlo-faf** [comment] 2020-02-21 14:51
Still. you can't repair it. Not sure if that is related to elevation. If i remember correctly you also can't repair loaded transports cause they refuse to land. So i guess you can't repair anything when it has not landed.

**Comment by Garanas** [comment] 2022-05-08 14:19
Closing this issue - a unit has to stand still in order for them to be repaired. In this example with the CZAR it can stand still, but it is almost impossible for a unit to reach all the way up. That sounds pretty sane to me.

**Closed by Garanas** 2022-05-08 14:19 UTC
Labels: area: engine, type: nice-to-have, priority: low
