### ISSUE TITLE
Water not rendering in game

### ISSUE THREAD

**Issue by Kiwasi** [FAForever/fa#3161] opened 2020-09-02 11:20 UTC
Very rarely water does not render, making the map appear to be entirely land.

The water still exists in the simulation. Naval units can still be built. ACUs still go under water and so on. 

My opponent reported normal rendering on their end.

Most recent issue was in this game. https://replay.faforever.com/12554335

**Comment by Garanas** [comment] 2020-09-21 20:41
If it happens again: open up moholog and check if there is some error or warning. Even better: share the entire log with us here. I cannot reproduce the bug with the given replay.

**Comment by speed2CZ** [comment] 2020-09-22 09:13
Try deleting cache C:\Users\%USERNAME%\AppData\Local\Gas Powered Games\Supreme Commander Forged Alliance\cache

**Comment by Garanas** [comment] 2022-05-07 09:36
Closing this issue - it has aged and I've not heard of it again.

**Closed by Garanas** 2022-05-07 09:36 UTC
