### ISSUE TITLE
FakeTeleportUnit doesn't work for UEF and Cybran

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#865] opened 2015-08-18 11:43 UTC
function FakeTeleportUnit from ScenarioFramework doesnt work for UEF and Cybran units,
giving the same warning for both factions http://pastebin.com/xr38sDrV

Seraphim and Aeon work no problem
After Coop update it wasnt working for no faction, this https://github.com/FAForever/fa/commit/5640ee708599cf10e6ca8531cc31a2c003103f28 fixed only Sera and Aeon

**Comment by ChrisKitching** [comment] 2015-08-18 16:37
Are you sure it's the same warning for both factions? That logic seems to handle both factions separately, and the log you gave is from inside the UEF branch.

This seems to be a regression vs. vanilla from the teleport effects rework that was done long ago. The code is as insane as you would expect.

**Comment by ChrisKitching** [comment] 2015-08-18 16:40
(The first like is even "no avatar unit specified for use during the UEF teleport effect", which seems unlikely to be in the output for the Cybran one)

**Comment by speed2CZ** [comment] 2015-08-18 18:12
Yes, same warning with cybran units. It shows the effect of uef building when you start construction, that cube, around the unit and gives this error. In both uef and cybran units

**Comment by duk3luk3** [comment] 2015-08-18 18:54
It makes sense that everything is working for aeon and seraphim because they use completely different effects.

However, you shouldn't see the UEF effect (or the UEF error) for both Cybran and UEF units, that doesn't make sense. Could you please give us the scenario file you have this happening in?

**Comment by duk3luk3** [comment] 2015-08-18 19:02
After a bit of Code reading it is quite obvious what is happening here. CreateMimicEntityOfUnit (https://github.com/FAForever/fa/blob/balance/3649/lua/EffectUtilities.lua#L1572) expects a "TeleportEffects.TeleportAvatarUnit" in the blueprint of the unit you're teleporting. I don't know what that is but I assume it's a special mesh for use as, well, a "teleport avatar". So you should fix your scenario code so that all UEF units you teleport have a teleport avatar, and we need to fix the code so fake teleport effects still work if there is no TeleportAvatarUnit.

**Comment by speed2CZ** [comment] 2015-08-18 19:13
Its in coop missions, Cybran M3, cybran vic trucks should leave through gate
https://github.com/FAForever/faf-coop-maps/blob/master/SCCA_Coop_R03/SCCA_Coop_R03_script.lua#L1120

then UEF M5, UEF Civ trucks and then ACU at the end of the mission
https://github.com/FAForever/faf-coop-maps/blob/master/SCCA_Coop_E05/SCCA_Coop_E05_script.lua#L2032

https://github.com/FAForever/faf-coop-maps/blob/master/SCCA_Coop_E05/SCCA_Coop_E05_script.lua#L2100

And then ofc in my mission, when I wanna use it on UEF civ trucks, sacu and acu. But no need to post it here since its the same as the examples above ^^

**Comment by duk3luk3** [comment] 2015-08-26 14:14
Someone needs to do this. Is there anybody who is familiar with the teleportation effects? I'd have to dig into this first, or I could just apply bandaids to every part that breaks.

**Comment by duk3luk3** [comment] 2015-08-30 08:13
Is this fixed by https://github.com/FAForever/fa/commit/5752b07f6e02603b55e1cce5b645b3eb01172ea0?

**Comment by speed2CZ** [comment] 2015-09-19 12:05
Its not bugging out anymore but the effect is really ugly since there's box around the units

**Comment by speed2CZ** [comment] 2015-09-19 12:08
![ss 2015-09-19 at 02 06 40](https://cloud.githubusercontent.com/assets/10947024/9976099/dc213f28-5ed7-11e5-9a3f-43a54c893ef5.png)

**Comment by aeoncleanse** [comment] 2016-01-04 00:18
This is going to have to wait for 3653 as long as it doesn't crash the game.

**Comment by aeoncleanse** [comment] 2016-03-11 15:14
Turns out this is deliberate, someone's idea of a pretty effect... Ugly as hell IMO, and I plan to remove it. Cybran trucks are affected because they register as UEF... Don't ask.

**Comment by aeoncleanse** [comment] 2016-03-11 15:29
d41b437245d089672bd242797b5905a914ecec71 and 195c117bf5bf1792779b1bfb6ed845a475cac9ef

**Closed by aeoncleanse** 2016-03-11 15:29 UTC
Labels: bug, high, sim
