### ISSUE TITLE
Game sometimes  Starts to a black screen right before loading animation

### ISSUE THREAD

**Issue by namidaka** [FAForever/fa#5307] opened 2023-08-02 22:28 UTC
Posted in the server repo because of the error code in lobby.lua
[game_20507620.log](https://github.com/FAForever/server/files/12245242/game_20507620.log)
```
Command line:
C:\ProgramData\FAForever\bin\ForgedAlliance.exe /init init.lua /nobugreport /log "%USER_PROFILE%\AppData\Roaming\Forged Alliance Forever\logs\game_20507620.log" /gpgnet 127.0.0.1:58417 /mean 1352.5756 /deviation 104.0993 /savereplay gpgnet://127.0.0.1:58415/20507620/%USER%.SCFAreplay /country FR /numgames 531 /numgames 446

Exit code: 1
Engine ver.: 3764
Game tick: 0

C++ Exceptions:
.?AUlua_RuntimeError@@
Main thread
@c:\programdata\faforever\gamedata\lua.nx2\lua\ui\lobby\lobby.lua 5500
CObject:.?AVCLobby@Moho@@, Table
@c:\programdata\faforever\gamedata\lua.nx2\lua\ui\lobby\lobby.lua 5511
Table
@c:\programdata\faforever\gamedata\lua.nx2\lua\ui\lobby\lobby.lua 5197
nil, -1, nil, Table, 16, 1, Table, true, Table
@c:\programdata\faforever\gamedata\lua.nx2\lua\ui\lobby\lobby.lua 7104
Table, nil, nil, nil, "attempt to call local `value' (a nil v

alue)", "...lua\ui\lobby\data\watchedvalue\watchedvaluetable.lua(54): attempt to call local `value' (a nil value)
stack traceback:
	...lua\ui\lobby\data\watchedvalue\watchedvaluetable.lua(54): in function <...lua\ui\lobby\data\watchedvalue\watchedvaluetable.lua:44>
	...ta\faforever\gamedata\lua.nx2\lua\ui\lobby\lobby.lua(7104): in function `ConvertObserverToPlayer'
	...ta\faforever\gamedata\lua.nx2\lua\ui\lobby\lobby.lua(5197): in function `Handle'
	...ta\faforever\gamedata\lua.nx2\lua\ui\lobby\lobby.lua(5511): in function <...ta\faforever\gamedata\lua.nx2\lua\ui\lobby\lobby.lua:5500>"


Debug messages:
```

**Comment by HUSSAR-mtrela** [comment] 2023-09-04 00:44
@Garanas this issue should be closed because it is a duplicate of issue #5301

**Closed** 2023-11-17 19:20 UTC
Labels: type: duplicate
