### ISSUE TITLE
Spread Attack ignores moved or deleted orders

### ISSUE THREAD

**Issue by MrNukealizer** [FAForever/fa#1927] opened 2017-04-19 01:02 UTC
As seen [here](https://youtu.be/l5awBANZpV8), spread attack doesn't properly update its copy of the unit orders if an order is deleted. That also applies to dragging orders around to move them. I've looked into it and there appears to be no event when an order is moved or deleted, so it would need to get a unit's current orders in SpreadAttack() instead of keeping a shadow copy when they're created. The problem is that it seems getting a unit's command queue from the UI side only gives target positions, not target entities.

**Comment by aeoncleanse** [comment] 2017-04-19 01:07
Duplicate of #1177

**Closed by aeoncleanse** 2017-04-19 01:07 UTC

**Comment by MrNukealizer** [comment] 2017-04-19 01:35
Oops, I looked but apparently not far enough back.

**Comment by aeoncleanse** [comment] 2017-04-19 09:24
That's OK, it brings it back to attention :)
