### ISSUE TITLE
uef t3 strategic sub doesn't launch nuke/ cybran t2 sub hunters not hitting uef t3 strategic sub

### ISSUE THREAD

**Issue by Justify87** [FAForever/fa#1313] opened 2016-05-24 21:41 UTC
replay id: 4635982

It's at the very end of the game. AchievedJaguar8 moves a t3 stategic sub to launch a nuke, it doesn't get launched or dies instantly, possiby because one of the torps from the t2 subs hit the nuke or the aoe destroyed the nuke. 

The torps from the t2 subs also don't hit the t3 sub in 90% of the time. Not sure if this is related to firing while moving of the t2 subs. Most of the torps "fly" above the sub and then hit the ground underneath the sub. 

Should a nuke from a t3 sub be destroyed/prevented from launch by enemie torps?

**Comment by aeoncleanse** [comment] 2016-05-24 22:19
This already has an issue, someone want to find it? May even have been fixed in 3652 can't remember.

**Comment by aeoncleanse** [comment] 2016-05-24 22:20
Duplicate of #1164

**Comment by shalkya** [comment] 2016-05-30 15:12
same issue as this #1312

**Comment by aeoncleanse** [comment] 2016-05-31 17:38
The bug with killing missiles is now fixed. The rest is duplicate of #1312

**Closed by aeoncleanse** 2016-05-31 17:38 UTC
