### ISSUE TITLE
Air units hitting shield dont trigger OnDestroy callback

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#2012] opened 2017-05-20 11:42 UTC
I tested it in 3rd UEF Missions.
Exact problem here https://github.com/FAForever/faf-coop-maps/blob/master/SCCA_Coop_E03/SCCA_Coop_E03_script.lua#L494
`CreatePlatoonDeathTrigger` doesnt work if any of the units hit the shield and bounce off
I did 3 tests with shields, 3 without, Everytime any of the air units hit the shield and bouned off, that trigger didnt fire.

**Comment by MrNukealizer** [comment] 2017-05-25 06:04
There seems to be something more to it than just air units hitting shields. I tested Cybran missions 1 and 2, which also use CreatePlatoonDeathTrigger for groups of air units, and they triggered properly after some of the air units bounced off shields.

**Comment by speed2CZ** [comment] 2017-05-25 06:10
My test was with mobile shields

**Comment by MrNukealizer** [comment] 2017-05-25 18:14
I tested all three missions with stationary shields and only UEF 3 broke. That seems to hint that it has something to do with the greater numbers, the presence of gunships, or possibly bouncing into water. I've looked at the shield bounce code but can't find anything that seems like it would change how the units die.

**Comment by MrNukealizer** [comment] 2017-06-11 05:27
I'm really getting the feeling it has something to do with the air units bouncing off the shield into water and sinking through the seafloor. I just had this happen on Cybran mission 5 with the gunship attack, and I notice what look like projectile falling under the map along the coast where dead gunships would've landed.  I also noticed that happening a lot on Black Day, but it didn't break the mission so I didn't put that much effort into finding the cause.

**Closed** 2017-06-19 18:52 UTC
Labels: bug, in progress, regression, sim
