### ISSUE TITLE
sera destroyers don't surface after building

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/fa#806] opened 2015-07-21 22:03 UTC

**Comment by quark036** [comment] 2015-07-22 17:05
this looks similar to #611, which was fixed with eb3a1f3

**Comment by Sheeo** [comment] 2015-07-22 17:19
Seems like it's a regression from that very commit:

    -	OnStopBeingBuilt = function(self, builder, layer)
    -		SSubUnit.OnStopBeingBuilt(self, builder, layer)
    -		IssueDive({self})
    -	end,

This code would make the subunit surface again.

**Comment by ChrisKitching** [comment] 2015-07-22 17:59
> This code would make the subunit surface again.

And reintroduce the very bug that commit fixes. They would once again toggle surfacedness when changing ownership.

That is not the solution.

**Comment by ChrisKitching** [comment] 2015-07-22 17:59
We probably instead want to just make the unit be built in the surface layer so we don't need to faff about issuing dive orders when it's built. We should similarly make aircraft be built in the air layer so we can throw away the code that babysits that particular thing.

**Comment by ChrisKitching** [comment] 2015-07-22 18:00
(Or possibly build it submerged and stay submerged. One or the other)

**Comment by quark036** [comment] 2015-07-22 18:55
Is there no detection to check if it is surfaced?

**Comment by Sheeo** [comment] 2015-07-24 11:28
So, testing this -- it turns out building the destroyer on land looks rather bad. It gets build in midair and floats downward until it hits the water layer.

I think we should go for the other solution.

**Closed** 2015-07-24 14:03 UTC
Labels: bug, regression, sim

**Comment by ChrisKitching** [comment] 2015-07-24 14:52
... wait, what?

Dont build it on land, build it in the water surface layer.

**Comment by bamboofats** [comment] 2015-07-24 17:17
![untitled-1](https://cloud.githubusercontent.com/assets/13047748/8880377/c15bea9c-326a-11e5-8646-7de87299c577.jpg)

This fix appears to bug out the destroyer textures. Now fresh out of the factory(left) still has the construction texture. Expected(right)

**Comment by ChrisKitching** [comment] 2015-07-24 17:30
The  recentCrotalus PR fixes this. Needs deployment. @sheeo

**Comment by Sheeo** [comment] 2015-07-24 21:57
Bamboofats please describe how you got the rendering to the right. Thats not tje expected rendering of the destroyer if you ask me...

**Comment by Sheeo** [comment] 2015-07-24 21:58
@cktitching please link the PR if it is relevant.

**Comment by ChrisKitching** [comment] 2015-07-24 22:01
https://github.com/FAForever/fa/commit/a46e5ca4b9ae4f47fa2f1182b61ee07364a4cd69

**Comment by bamboofats** [comment] 2015-07-25 03:55
![untitle3](https://cloud.githubusercontent.com/assets/13047748/8887774/2db89c6e-32c3-11e5-9260-9ef8b66622f6.jpg)
Well, the rest of the navy looked like this, so I sort of figured the destroyer bugged out.  Anyway for the first picture i posted, the right one was spawned by the console and is the look im used to. The left one was built by the factory.  
Team colour blue, bloom on
