### ISSUE TITLE
should unit consumption ui display the real consumption ?

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2439] opened 2018-04-03 04:22 UTC
![image](https://user-images.githubusercontent.com/11618427/38228996-c8c3ce44-3749-11e8-8ffc-fd9c48ed22ab.png)

here as you can see, the unit display on the "ideal" (when not stalling) consumption (especially for e) and not the real consumption that you can see on the top right.

should we display the real consumption ?

**Comment by speed2CZ** [comment] 2018-04-03 06:18
I'do go with no

Else it would be hard to find the cause of the stall. You'd be checking all the units and they would all show that everything is perfect

**Comment by shalkya** [comment] 2018-04-03 07:02
not really, since if you mass stall, then the e appear as "ideal" (atm) but the mass already appear as "real". With the change you would only change the e from ideal to real.
as for the e stall, then it's the opposite. it would change ideal mass consumption to real mass consumption.

**Comment by CookieNoob** [comment] 2018-04-03 16:45
then it looks like the cost of the unit is changed due to the stall, i.e. in your picture it would show that the sacu uses
-43 mass
-9 power
which is the wrong ratio of power/mass and doesnt reflect the actual cost. I wouldnt change it either.

**Comment by HUSSAR-mtrela** [comment] 2018-07-10 15:10
@aeoncleanse this is not a bug and we can close it

**Comment by MrRowey** [comment] 2021-11-07 23:53
@Garanas close this based on hussar stating this is not a bug

**Closed** 2021-11-08 00:11 UTC
Labels: type: question
