### ISSUE TITLE
All transports in the game ignore sera's ACU regen field

### ISSUE THREAD

**Issue by K-ETFreeman** [FAForever/fa#5284] opened 2023-07-27 11:16 UTC
All transports in the game ignore sera's ACU regen field (They get neither regen nor max HP bonus)
It is working for other air units, so i guess its a bug and not a feature
![faf-regen-field-bug-screen](https://github.com/FAForever/fa/assets/55841348/0624cb0c-518c-40bf-ae96-f106b2767c1d)

**Comment by haifron** [comment] 2023-09-29 20:20
Duplicate of #4368

**Closed** 2023-10-15 20:18 UTC
Labels: status: new issue
