### ISSUE TITLE
Cybran ACU starts walking while assisting mex

### ISSUE THREAD

**Issue by Totaltuna** [FAForever/fa#1318] opened 2016-05-26 15:30 UTC
Cybran ACU starts walking when you tell it to assist a mex, not sure if it's exclusive to cybran but only had it happen with cybran ACU

**Comment by Justify87** [comment] 2016-05-26 16:50
It also starts walking while assisting a shield upgrade. 
There is also a bug with a successfull assistance on a shield upgrade. If I cue more than one upgrade the acus progress bar remains full when the second upgrade starts. Mass and energy ist used but the upgrade doesn't get faster.

**Comment by aeoncleanse** [comment] 2016-05-26 20:21
Duplicate of #1256

**Closed by aeoncleanse** 2016-05-26 20:21 UTC
