### ISSUE TITLE
Warning in log when moving cursor over units without icon

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#965] opened 2015-10-19 11:16 UTC
If you open cheat menu and move cursor over unit without icon, you will get this warning:
```
WARNING: Warning: Unable to find file: /textures/ui/cybran/icons/units/avataruel0001_icon.dds
WARNING: stack traceback:
WARNING:         ...ramdata\faforever\gamedata\lua.nx2\lua\ui\uiutil.lua(360): in function <...ramdata\faforever\gamedata\lua.nx2\lua\ui\uiutil.lua:329>
WARNING:         (tail call): ?
WARNING:         ...iance\gamedata\lua.scd\lua\ui\dialogs\createunit.lua(451): in function <...iance\gamedata\lua.scd\lua\ui\dialogs\createunit.lua:442>
WARNING:         ...iance\gamedata\lua.scd\lua\ui\dialogs\createunit.lua(499): in function <...iance\gamedata\lua.scd\lua\ui\dialogs\createunit.lua:497>
```
First line is changing depending on the unit ofc...

Its the case since few patches ago

**Comment by duk3luk3** [comment] 2015-10-19 11:24
This is normal. Closing as duplicate of #895

**Closed by duk3luk3** 2015-10-19 11:24 UTC
Labels: regression

**Comment by speed2CZ** [comment] 2015-10-19 11:25
Normal? it wasnt happening before, so how can this be normal?

**Comment by duk3luk3** [comment] 2015-10-19 11:27
If you look at #895, I reported almost exactly the same error happening for exactly the same "Move cursor over unit without item in cheat menu", so you're wrong about "wasn't happening before", it's always been there.

**Comment by ChrisKitching** [comment] 2015-10-19 17:23
To be clear, the thing that's "new" (as of quite a few months back now) is that it prints a warning in the log when it tries to load a UI file that doesn't exist (this was quite helpful when redoing the lobby).

Previously, it would silently fail, which was quite irritating.
