### ISSUE TITLE
Possible to build factory using hotbuild

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#1108] opened 2016-01-21 12:55 UTC
STR:

- Have t1 factory assist t2 factory
- Use 'w' binding to issue engineer in t1 factory
- t1 fac will build a t2 support factory

**Comment by aeoncleanse** [comment] 2016-01-21 12:59
This will be fixed by duk3's engiemod rewrite.

**Comment by duk3luk3** [comment] 2016-01-21 13:08
This is an exact duplicate of #1043.

**Closed by duk3luk3** 2016-01-21 13:08 UTC
Labels: bug

**Comment by Sheeo** [comment] 2016-01-21 14:02
Then why is that issue closed?
