### ISSUE TITLE
can we have a save restrictions option in the restrictions menu?

### ISSUE THREAD

**Issue by imazombie358** [FAForever/fa#2467] opened 2018-05-17 20:03 UTC
one of the reasons i love to play faf is for the insane level the unit restriction system goes to. this is extremely useful when playing with ai, especially with the ability to prevent t1 spam. 

but each time i play with faf, i have to go through and tediously check all the units i want restricted. i understand there are buttons above the units that allow for easier mass-restriction, but because i prefer to play with ai, i use this system to satiate my picky self when playing supcom, and there are so many different combinations that having the ability to SAVE the settings as you would a game would benefit myself and other frequent ai users greatly. 

an example of this being useful is, think of all that has to be done to make it so the ai only builds t1 land spam. although this is unlikely, the amount of work required for this kind of game is stupidly tedious.

although i do enjoy being able to have such precise restrictions, it is by far(for me) the biggest task of playing with faf to set each restriction at the beginning of each game.

**Comment by shalkya** [comment] 2018-05-28 00:37
can't you just use presets ?

**Comment by imazombie358** [comment] 2018-05-30 04:40
no. i tried and the presets thing did not work. i spent 10 minutes setting up restrictions for a boats only game compatible with the ai and mods i use. 

this meant nothing that the ai would spam that would be useless in a boats-only battle,

i started the game and found that fa had not included a necessary mod i play with so i restarted. 

i set up another game and found out that the damn presets save game thing diiiid noooot work. so fuck that. please make a restrictions-specific save thing please. 

i wouldnt play faf if normal supcom had just the restrictions system that faf has. i swear, I WOULD LOVE TO KNOW IF THAT RESTRICTIONS THING IS A MOD AVAILABLE OUTSIDE OF FAF. 

faf is useful to me ONLY in the vault and that restrictions thing. it is far too multiplayer oriented for me to make more use of it, as i do not want to play with other people, which is what faf is almost exclusively made for. i hate how all these games today are so damned multiplayer oriented.

**Comment by shalkya** [comment] 2018-05-30 06:40
weird, preset works very well for me when i want to put restriction. Are you using it well ?

well it's true that most of us just consider not playing on multiplayer to be lame, and that is it just scratching the surface of the depth that this game as to offer.
I guess you have to deal with what the majority of people wants.

**Comment by HUSSAR-mtrela** [comment] 2018-07-10 15:01
I will investigate this issue and let you know if we can implement saving of unit restrictions.

**Comment by HUSSAR-mtrela** [comment] 2018-08-06 14:58
closing this because we cannot reproduce this issue and unit-restrictions are saved/loaded as expected.

**Closed by HUSSAR-mtrela** 2018-08-06 14:58 UTC
Labels: enhancement, question
