### ISSUE TITLE
`speed` (a nil value)

### ISSUE THREAD

**Issue by micheljung** [FAForever/fa#1059] opened 2015-12-15 23:18 UTC
Popped up in a test game:

    WARNING: Error running OnFrame script in CScriptObject at 100682c0: ...ramdata\faforever\gamedata\lua.nx2\lua\maui\text.lua(78): attempt to perform arithmetic on upval `speed' (a nil value)
         stack traceback:
         	...ramdata\faforever\gamedata\lua.nx2\lua\maui\text.lua(78): in function <...ramdata\faforever\gamedata\lua.nx2\lua\maui\text.lua:75>

**Comment by aeoncleanse** [comment] 2015-12-15 23:21
Was this beta or not? It *should* be fixed in beta I think.

**Comment by micheljung** [comment] 2015-12-15 23:49
You're right, the game was not hosted as beta.

**Comment by duk3luk3** [comment] 2015-12-16 08:08
FTR: Duplicate of #874, #1032

**Comment by duk3luk3** [comment] 2015-12-16 08:12
Actually release/3652 branch does not have the fix in it. Someone needs to apply #880...

**Comment by aeoncleanse** [comment] 2015-12-16 14:21
I agree with chris from before. We want this to spam the log with errors, since it doesn't crash the game, so that we can find and fix all places StreamText us used improperly. We don't want to defensively set speed. The lobby one is fixed.

**Comment by duk3luk3** [comment] 2015-12-16 14:46
Well then do that already!

> or alternatively make a patch that throws an error in the StreamText constructor.

The way it is now, where the error will be coming from an anonymous function resulting in no usable backtracke, is just bullshit.

**Comment by aeoncleanse** [comment] 2015-12-16 14:49
I'm not actually sure how you'd go about making an error which shows you what called StreamText. Can you whip it up and PR?#

**Comment by duk3luk3** [comment] 2015-12-16 14:54
If you want the log "spammed" there isn't a good way. You need to do something like setting `self.createdby = debug.traceback()` in the constructor and then doing `if not speed then log.warn('Someone forgot to set speed when creating this StreamText',self.createbdy) end` in the OnFrame function.

**Comment by Sheeo** [comment] 2015-12-17 02:44
Why is there not just a sensible default for the speed value?

**Comment by duk3luk3** [comment] 2015-12-17 08:19
Because apparently that's not The Right Thing[tm] to do.

**Closed** 2015-12-29 12:13 UTC
