### ISSUE TITLE
UEF SCUs can't make t2 support factories if you have only t2 HQ

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/fa#782] opened 2015-07-18 00:26 UTC
If you have an t3 HQ however, they can make both t2 and t3 support factories.

Tested with UEF SCUs and land factories, not with others.

**Comment by Varaxis** [comment] 2015-07-20 20:19
Cannot confirm the bug in sandbox. http://i.imgur.com/sYDs8hW.jpg

Might be related to the issue to where you adopt a base through full share, and it doesn't recognize that you have a HQ for quite some time. Faster to build a new one to get the support facs working as expected. Much faster to build a new HQ usually, to enable support facs, than to wait whatever the interval is that it is checked for again. If it only had t2 land HQ (got to t3 and scu through air, navy, or ACU), upgrading it to t3 HQ would work too.

**Comment by aeoncleanse** [comment] 2016-07-03 00:50
This should have been fixed by 3652, but it needs confirming

**Comment by JaggedAppliance** [comment] 2016-09-20 22:46
I couldn't reproduce the bug.

**Comment by aeoncleanse** [comment] 2016-09-20 22:50
Nor can I. Closing.

**Closed by aeoncleanse** 2016-09-20 22:50 UTC
Labels: bug, sim
