### ISSUE TITLE
This line is wrong... pretty sure

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/fa#3176] opened 2020-10-01 14:05 UTC
https://github.com/FAForever/fa/blob/c03958dacbec35e92ee7050a3c21314ed687c632/lua/ui/dialogs/score.lua#L566

This if won't works because the client copies the currently executed init file into the init.lua and does not keep the _ladder postfix. I am not sure if that "if" not working has negative consequences but it should definitely be deleted.

**Comment by axel1200** [comment] 2020-10-01 14:06
GetCommandLineArg('/init', 1)[1] will in 100% of cases return "init.lua"

**Comment by speed2CZ** [comment] 2020-10-01 16:19
When did this got changed?

**Comment by axel1200** [comment] 2020-10-01 16:23
Java client always had this behavior

**Comment by MrRowey** [comment] 2021-11-08 00:38
@Garanas idk what to make of this just know you were talking in zulip about the init files :)

**Comment by Garanas** [comment] 2021-11-08 06:34
This is not part of the init file though. It is wrong - but I'm not sure if we want it to work.

**Comment by Garanas** [comment] 2022-05-07 09:36
Closing this issue - it has aged. Everything works as intended at the moment.

**Closed by Garanas** 2022-05-07 09:36 UTC

**Comment by 1-alex98** [comment] 2022-05-09 12:05
https://github.com/FAForever/fa/blob/c03958dacbec35e92ee7050a3c21314ed687c632/lua/ui/dialogs/score.lua#L566
just makes the code more complex
