### ISSUE TITLE
 near finish shield get kill and reset health of com

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1094] opened 2016-01-15 16:53 UTC
http://forums.faforever.com/forums/viewtopic.php?f=3&t=11145

**Comment by duk3luk3** [comment] 2016-01-15 19:06
The health loss does not come from a normal attack since OnDamage is not called. Very interesting.

**Comment by duk3luk3** [comment] 2016-01-15 20:23
The shield actually got finished and blinked on for a tick, when it was already destroyed. That probably has something to do with the glitch.

**Comment by zlo-faf** [comment] 2016-01-16 12:14
http://forums.faforever.com/forums/viewtopic.php?f=63&t=11300

Another example and replay where i reproduced bug

**Comment by duk3luk3** [comment] 2016-01-16 12:36
Thanks!

**Comment by Crotalus** [comment] 2016-01-16 15:38
A known bug, fixed in release/3652 here: 
https://github.com/FAForever/fa/commit/0822d1043b5dfe54e7d77d6daae8b6a71b75827a

Seems like not only sinking structures had the no-collision flag set, also structures that get animated at death (like a shield).

**Comment by duk3luk3** [comment] 2016-01-16 16:21
Huh I don't understand why I didn't find that SetHealth call in my debugging.

**Comment by Nojoke185** [comment] 2016-10-03 23:01
anymore reports of this or solved?

**Comment by Crotalus** [comment] 2016-10-03 23:51
Solved as mentioned earlier, closing.

**Closed by Crotalus** 2016-10-03 23:51 UTC
Labels: in progress, need verification
