### ISSUE TITLE
Drop connection to faf because of map id from vault

### ISSUE THREAD

**Issue by RHode007** [FAForever/fa#3856] opened 2022-05-10 22:49 UTC
**Describe the bug**
I coppied map id from vault and paste it in lobby chat then faf client and ice lost connection to servers, faf reconnect itself after sec and need just reconnect to game

**To Reproduce**
1. join lobby
2. go to vault and copy any map id (via right button on id in client)
3. paste in lobby chat and send

**Expected behavior**
its just a message?

**Additional context**
game_.log
2022-05-11 01:27:19.832 DEBUG 8572 --- [JJsonPeer] c.f.c.fa.relay.ice.IceAdapterCallbacks   : Message from game: 'Chat' '["#6 721"]'
2022-05-11 01:27:19.833 DEBUG 8572 --- [JJsonPeer] com.faforever.commons.lobby.FafLobbyApi  : Outbound message: {"command":"Chat","args":["#6 721"],"target":"game"}
2022-05-11 01:27:19.901  INFO 8572 --- [reactor-tcp-nio-1] com.faforever.commons.lobby.FafLobbyApi  : Outbound channel cancelled
2022-05-11 01:27:19.901  INFO 8572 --- [reactor-tcp-nio-1] com.faforever.commons.lobby.FafLobbyApi  : Inbound channel cancelled
2022-05-11 01:27:19.902  INFO 8572 --- [reactor-tcp-nio-1] com.faforever.commons.lobby.FafLobbyApi  : Disconnected from server
2022-05-11 01:27:19.902  INFO 8572 --- [reactor-tcp-nio-1] com.faforever.commons.lobby.FafLobbyApi  : Attempting to reconnect
2022-05-11 01:27:19.902 DEBUG 8572 --- [reactor-tcp-nio-1] com.faforever.commons.lobby.FafLobbyApi  : Starting session listener
2022-05-11 01:27:19.902 DEBUG 8572 --- [reactor-tcp-nio-1] com.faforever.commons.lobby.FafLobbyApi  : Starting login listener
2022-05-11 01:27:19.971  INFO 8572 --- [reactor-tcp-nio-1] com.faforever.commons.lobby.FafLobbyApi  : Connected to lobby.faforever.com on port 8002
2022-05-11 01:27:19.972 DEBUG 8572 --- [reactor-tcp-nio-1] com.faforever.commons.lobby.FafLobbyApi  : Outbound message: {"command":"ask_session","version":"2022.4.1","user_agent":"downlords-faf-client"}

![image](https://user-images.githubusercontent.com/19503512/167738708-23659fd2-cf8d-42f1-9cdb-e0ceaf0763f3.png)

ice-adapter.log
2022-05-11 01:27:17.992 INFO  Received GPGNet message: ClearSlot 8 (c.f.iceadapter.gpgnet.GPGNetServer:123)
2022-05-11 01:27:19.830 INFO  Received GPGNet message: Chat #6 721 (c.f.iceadapter.gpgnet.GPGNetServer:123)
2022-05-11 01:27:29.035 ERROR Error while communicating with FA (input), assuming shutdown (c.f.iceadapter.gpgnet.GPGNetServer:160)
java.io.EOFException: null
	at com.google.common.io.LittleEndianDataInputStream.readAndCheckByte(LittleEndianDataInputStream.java:226)
	at com.google.common.io.LittleEndianDataInputStream.readInt(LittleEndianDataInputStream.java:116)
	at com.faforever.iceadapter.gpgnet.FaDataInputStream.readInt(FaDataInputStream.java:56)
	at com.faforever.iceadapter.gpgnet.FaDataInputStream.readString(FaDataInputStream.java:65)
	at com.faforever.iceadapter.gpgnet.GPGNetServer$GPGNetClient.listenerThread(GPGNetServer.java:150)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-05-11 01:27:29.036 INFO  GPGNet connection lost (c.f.iceadapter.gpgnet.GPGNetServer:186)
2022-05-11 01:27:29.037 DEBUG Closing GPGNetClient (c.f.iceadapter.gpgnet.GPGNetServer:169)
2022-05-11 01:27:29.038 INFO  FA SHUTDOWN, closing everything (com.faforever.iceadapter.IceAdapter:131)
2022-05-11 01:27:29.039 WARN  Close requested, stopping... (c.f.iceadapter.rpc.RPCHandler:130)
2022-05-11 01:27:29.039 INFO  close() - stopping the adapter (com.faforever.iceadapter.IceAdapter:142)
2022-05-11 01:27:29.039 DEBUG No longer listening for GPGPNET from FA (c.f.iceadapter.gpgnet.GPGNetServer:163)
2022-05-11 01:27:29.042 INFO  GPGNetServer stopped (c.f.iceadapter.gpgnet.GPGNetServer:262)

**Comment by Garanas** [comment] 2022-05-11 05:40
> go to vault and copy any map id (via right button on id in client)
Could you add a screenshot? I've never been able to copy a map id

**Comment by MrRowey** [comment] 2022-05-11 08:12
![image](https://user-images.githubusercontent.com/20344151/167800938-71430e40-db94-4a69-a1ff-80e6bb8460b8.png)
So i assume this is the MapID if so tried to reproduce and could not get this error. Host & Joined lobby Could not reproduce the same issues

**Comment by Garanas** [comment] 2022-05-11 09:17
I tried it with a copy of the replay id - can't make it malfunction with that either.

**Comment by RHode007** [comment] 2022-05-11 12:04
Seems comma fix the problem, but i dont have it in russian 
win 11 faf client 2022.4.1 

> ru 
![image](https://user-images.githubusercontent.com/19503512/167838081-0a8f31b6-c746-4ad6-b82d-9e4d81ab9393.png)
> eng 
![image](https://user-images.githubusercontent.com/19503512/167839054-bda5cfc3-37e2-4cae-a1c9-ba19e127fa30.png)
> de 
![image](https://user-images.githubusercontent.com/19503512/167841486-f02d62c5-dd5c-4884-8a51-c9399cc90ef5.png)
italian have dot too

seems this needs to be moved to another repo but it may also be necessary to allow unicode \xa0 or handle and delete it on the client before sending

**Comment by MrRowey** [comment] 2022-05-11 12:15
This is a client issues as that is just an id of number for me and with your language setting seems to cause the issue. @Sheikah45

**Comment by Garanas** [comment] 2022-06-12 13:52
Closing this issue - I think Sheikah is right here.

**Closed by Garanas** 2022-06-12 13:52 UTC
Labels: status: novel issue
