### ISSUE TITLE
inconsistent template behaviour with mexes

### ISSUE THREAD

**Issue by Farmsletje** [FAForever/fa#2789] opened 2019-05-27 16:23 UTC
see https://www.youtube.com/watch?v=R5UBZu9yINc&feature=youtu.be

**Comment by Farmsletje** [comment] 2019-05-27 17:15
I see what the issue is now. It usually has the 'construction' & 'selection and storage' tab enabled which results in it defaulting to the first one (construction) so you have to click on the selection & storage tab to be able to save the template. However it sometimes only has the 'selection and storage' tab enabled which results in it defaulting to that one. Still don't know why the behaviour is inconsistent though

**Comment by speed2CZ** [comment] 2019-05-27 18:37
I would say that if you first select a unit that can be upgraded, it opens the constuction tab. If the first selected unit cant be upgraded it opens the selection tab (which can create templates). And from the video it seemed pretty consistent.

**Comment by HUSSAR-mtrela** [comment] 2019-12-24 22:08
@aeoncleanse I agree with @speed2CZ  and we should close this as not a issue.

**Comment by shalkya** [comment] 2019-12-26 18:04
well what could be possible would be to switch to selection tab if you select more than 1 type of building that can upgrade.
eg : 
select a T1 mexx => default to construction tab
- then select a T1 mexx stay on construction tab
- or select any other type of building => change to selection tab

**Comment by zlo-faf** [comment] 2020-02-21 15:02
So the issue is that it is not obvious, that you should go to the correct tab in order to make a template. 
Issue also should apply to all upgraideble structures.
If you watch "how to make a template" tutorial again you should be able to save a template after that.
selecting mass extractor and other stuff that can't be upgraided and still being able to queue an upgraide sounds like a positive feature to me. This issue should be closed or at least renamed.

**Closed** 2022-06-12 23:18 UTC
Labels: type: not-a-bug
