### ISSUE TITLE
sera T2 torpedo launcher torpedo's block sera destro beam

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2121] opened 2017-07-24 13:41 UTC
![image](https://user-images.githubusercontent.com/11618427/28526000-662d8f52-7086-11e7-87bb-fcc0706250ef.png)
make quite some big balance issue, since the T2 torpedo launcher is nearly un-killable by sera destro

**Comment by CookieNoob** [comment] 2017-07-25 09:21
it's probably trying to target a bone which is under water
https://github.com/FAForever/fa/blob/develop/units/XSB2205/XSB2205_unit.bp
```
TargetBones = {
    'Abovetgt',
    'XSB2205',
},
```

I really doubt that the torpedos (which are underwater) would block the beam of the destroyer

**Comment by shalkya** [comment] 2017-07-25 17:52
i'm sorry, i should have post the replay. And it is really the bone of the torpedo that block the beam (!)
here it is : content.faforever.com/faf/vault/replay_vault/replay.php?id=6543057
log here : https://gist.github.com/shalkya/a8d689a200a97a64f3f74b0ce1ed17a4

**Comment by CookieNoob** [comment] 2017-07-31 07:58
you are correct, the beam hits the torpedos directly and is still over the water surface. I couldnt reproduce it at first since my dev version of the game loads FA and nomads from the git repo and for some reason the issue is not present when using nomads as well.

**Comment by speed2CZ** [comment] 2019-07-14 15:11
Since they are fired above the water, they don't travel that deep and their hitbox is much higher, so easy for beam weapons to hit them

![ForgedAlliance_2019-07-14_17-09-48](https://user-images.githubusercontent.com/10947024/61185468-41a34f80-a65a-11e9-8089-d2e400a27161.png)

**Comment by MrRowey** [comment] 2024-06-19 20:04
@clyfordv or @lL1l1 would either fo you be interesting in fixing this relatively small bug

**Comment by lL1l1** [comment] 2024-09-09 14:24
Tested it, beams do not collide with the beam. Fixed by #5447.

**Closed by lL1l1** 2024-09-09 14:24 UTC
Labels: type: bug, area: sim
