### ISSUE TITLE
"SACU's presets needs different EXP"

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/fa#3446] opened 2021-09-22 21:22 UTC
"SACU's presets need differet exp for veterancy. Maybe it's depends of their mass costs. Can you fix it,please."

From https://github.com/FAForever/downlords-faf-client/issues/2352

@FunnySqirrel

**Comment by Sheikah45** [comment] 2021-09-23 03:27
I could actually transfer the issue so I did it manually

**Comment by FunnySqirrel** [comment] 2021-09-23 07:30
oh, Thank you so much.

**Comment by Tagada14** [comment] 2021-10-03 09:47
I am not quite sure I understand what the issue/bug is here? All units need to kill a certain amount of mass in order to get a vet level, that amount depends on their mass cost and is either x2, x1.5, x1.25 (IIRC) of their cost depending on the specific unit.

**Comment by Garanas** [comment] 2021-10-03 10:10
I think the issue is that when you'd enhance a barebone SACU to rambo set, or make a Rambo SACU directly then they wouldn't share the same vet requirements.

**Comment by Tagada14** [comment] 2021-10-04 15:47
Yeah, a known issue, fixed soon tm with the SACU rebalance.

**Comment by MrRowey** [comment] 2023-04-05 21:36
@Tagada14 is this still being addressed in the current SACU PR ?

**Closed** 2023-12-27 17:34 UTC
Labels: area: balance, area: sim, status: in-progress, priority: low
