### ISSUE TITLE
Observers are just straight up broken

### ISSUE THREAD

**Issue by DragonStrike406** [FAForever/fa#3179] opened 2020-10-04 10:54 UTC
As the title says, observers are broken. If you run a match with observers on, and you do have an observer waiting for the game then as soon as the match loads you're greeted with the connection issues screen. There you see the observer as the one that's silent, and after the time period you can eject them. I have no idea how it works from the observer's perspective.

**Comment by Garanas** [comment] 2022-05-07 09:34
Closing this issue - unable to reproduce and the issue is dated.

**Closed by Garanas** 2022-05-07 09:34 UTC
