### ISSUE TITLE
Janus bombs track to units and buildings instead of dropping in a line

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#2407] opened 2018-03-09 13:46 UTC
So this bug will just not die, it's still around and is as bad as ever. It also seems to be present in the scorcher (UEF T1 bomber).

**Comment by CookieNoob** [comment] 2018-04-09 18:25
it's not tracking.... the bombs are just launched in the direction of the estimated target position.
try to play around with these values:
https://github.com/FAForever/fa/blob/22737d8080277b0bc7b3752bab538c7d81578b83/units/DEA0202/DEA0202_unit.bp#L507-L512

**Comment by JaggedAppliance** [comment] 2018-04-16 11:46
Ok, thanks for the tip cookie. I'm aware it's not technically tracking but that word describes the behaviour well imo.

**Comment by CookieNoob** [comment] 2018-04-16 16:01
the important thing is that there is tracking in the game. I.e. anti air missiles track their targets, in the nomads mod there are several missiles that do that too (or did until I changed it recently)... so it's a bit misleading when you speak about tracking

**Comment by MrRowey** [comment] 2021-11-07 23:51
@Garanas this can be closed as it is not a bug or maybe just get the balance team to see if this is something they want to change or not

**Comment by Garanas** [comment] 2021-11-08 00:10
This is a known issue and should be solved by https://github.com/FAForever/fa/pull/3509.

**Comment by MrRowey** [comment] 2022-04-17 13:12
@Garanas this one fixed ?

**Comment by Garanas** [comment] 2022-04-17 13:53
No, still very much alive.

**Comment by Ejsstiil** [comment] 2023-11-23 19:42
Bombs actually does some kind of tracking, see the video, when I try to teleport my commander who was locked-on by enemy DEA, to the different locations during DEA's bomb run:

following explains that every bomb is locked to the target's position before it is ejected/spawned, and the target vector is adjusted for every upcoming next bomb.

https://github.com/FAForever/fa/assets/36369441/abd23159-835a-4d04-981d-fe488a750ab6

Next video shows when I increase the number of bombs to drop and make the bones fire sequentially, or - in other words - make the releasing much slower, the late bombs can go even backwards as they sticks to the target location:

https://github.com/FAForever/fa/assets/36369441/57f721da-9b97-4575-9af2-17923a2bbd8f

**Closed** 2023-12-16 20:21 UTC
