### ISSUE TITLE
Engineers assist nuke at an incorrect level

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/fa#1166] opened 2016-03-22 23:23 UTC
Engineers went from the normal spend on nuke assist (-0m, -40e) to (-7m, -520e) after launching a nuke.  The nuke started being constructed at a much faster rate.

Replay 4569130, ~31 mins into game, Softles' nuke launcher.

As yet unable to reproduce in sandbox.

**Comment by aeoncleanse** [comment] 2016-03-22 23:48
Duplicate of #1159 ?

**Comment by HardlySoftly** [comment] 2016-03-23 09:15
The engineers were set to assist the nuke building not the com, so it is different to the issue described in #1159

**Comment by aeoncleanse** [comment] 2016-03-23 13:06
Righto. Is this a regression or an old bug?

**Comment by Crotalus** [comment] 2016-03-23 16:08
Well, the ACU (which built the nuke) was upgrading when the engineer's updated their consumption between nukes so this is the same issue. Something that's been in the game for a very long time.

**Comment by aeoncleanse** [comment] 2016-04-01 17:35
I need confirmation this was fixed withh #1159

**Comment by Exotic-Retard** [comment] 2016-04-07 00:19
just tested it and it appears fixed, reproduced it in 3650 but not in beta. hope this helps

**Closed** 2016-04-07 01:29 UTC
Labels: need verification
