### ISSUE TITLE
in game mod manager showing mods as requiring dependencies.

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#1186] opened 2016-03-31 17:58 UTC
http://puu.sh/o0X8c/afb2a4c5af.jpg

see picture for explanation - in lower right corner we see i have 11 ui mods activated, in the mod manager i have 9 since it thinks that those 2 are disabled because they lack dependencies (which i have). the mods also run in game. so this is a purely display bug it seems.

hope this helps

**Comment by HUSSAR-mtrela** [comment] 2016-03-31 18:26
I will try to reproduce this issue. Those disabled mods might depend on a newer version of the common mod than v1.0 that you have. Can you check if those disabled mods have UID in "requires" table (mod_info.lua) and it is matching UID of the common mod?

**Comment by Exotic-Retard** [comment] 2016-04-05 17:00
sorry for not replying earlier. the UIDs match for both mods. 
requires = {"zcbf6277-24e3-437a-b968-Common-v1"}
is in both and the uid of the common mod tools that i have is: 
uid = "zcbf6277-24e3-437a-b968-Common-v1"

since those mods are working in game, i kinda expected them to be set up properly.

hope this helps

**Comment by aeoncleanse** [comment] 2016-04-05 19:12
@HUSSAR-mtrela  -  We should also be using the right buttons in the Mod Manager. It should be consistent with the buttons used throughout the rest of the lobby.

**Comment by HUSSAR-mtrela** [comment] 2016-04-05 19:50
thanks @Exotic-Retard for checking uid 
@aeoncleanse Well, they are not just click buttons but rather custom toggle buttons because standard toggle buttons are too big since their are sized by their background image. I will see if I can change the background texture so it look like more like in other buttons.

**Comment by aeoncleanse** [comment] 2016-04-05 21:37
The standard buttons are fine, trust me, and they work fine for toggles too. They can be easily arranged relative to the background group, or anything else for that matter :) Alternatively, use a simple checkbox as elsewhere, but I won't be shipping with these buttons, they're far too out-of-place. Just check how similar functions have been done elsewhere in the lobby. Pretty sure we had toggles for this too.

**Comment by HUSSAR-mtrela** [comment] 2016-04-11 02:31
![mods-filters](https://cloud.githubusercontent.com/assets/11665978/14415325/c545afc0-ff6b-11e5-9796-d7ab9cec5fab.png)

I updated styling of filter buttons and now they match other buttons

**Comment by aeoncleanse** [comment] 2016-04-11 16:20
Nicely done :)

**Comment by HUSSAR-mtrela** [comment] 2016-04-12 02:34
@Exotic-Retard I need more info to reproduce this issue, Can you send me list of mods that you enabled when the issue with disabled mods, has occurred? Your screenshot is in Russian AFIK so can you please translate to English status of mods displayed on the right side?

**Comment by HUSSAR-mtrela** [comment] 2016-04-12 02:39
Also, where can I get your mods because I cannot find them in the vault?
- abus[e
- Additonal Camera stuff

**Comment by Crotalus** [comment] 2016-04-12 20:11
Is this a problem with 3652? I have issues with mod dependencies in current FAF version but in 3652 it works fine for me.

**Comment by HUSSAR-mtrela** [comment] 2016-04-13 03:03
@Crotalus, there might be an issue with mod dependencies. However I cannot reproduce this issue because I dont have all mods that Exotic is using.

**Comment by aeoncleanse** [comment] 2016-04-14 21:36
I, too, have been unable to reproduce this issue

**Comment by HUSSAR-mtrela** [comment] 2016-04-15 03:43
I added a few log messages which should help identify root cause for this and other potential issues with selecting mods in the ModsManager. 
https://github.com/FAForever/fa/pull/1187/commits/e8d7c1a03244f070918020303080dd05ffeff7c4
I think we should close this issue if @Exotic-Retard cannot provide detailed steps to reproduce this issue.

**Comment by Exotic-Retard** [comment] 2016-04-15 11:56
.. actually it seems i cannot reproduce the issue either xdd
it seems to have just vanished and now everything is working correctly.
tested both faf and faf beta and it worked just fine, selecting same map, ect did not change anything either
perhaps we can close this issue and pretend it was fine all along?
sorry for bothering everyone with this i guess : /

**Closed** 2016-04-15 12:00 UTC
Labels: bug, low, need verification, ui

**Comment by HUSSAR-mtrela** [comment] 2016-04-15 13:38
@Exotic-Retard when you noticed this issue, do you remember if you hosted a game or did you join a game hosted by someone else? I asked because ModsManager is checking for mods that are missing by other players and disables them. However, that should happen only for SIM mods but and not UI mods that you reported this issue.
