### ISSUE TITLE
Problems with restricting sACU upgrades

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1427] opened 2016-08-10 18:37 UTC
http://forums.faforever.com/viewtopic.php?f=3&t=12902&p=132585

> What seems to be problem(s): 
> 1) Restricted sACU's RAS removes templates for RAS presets from sACU factory , but after sACU built the RAS upgrade still can be ordered manually. Other sACU upgrades show same behavior , removing of sACU preset containing upgrade from factory, but allowing to build restricted upgrade manually. 
> 2) Interestingly enough, restricting sACU without restricting sACU factory removes sACU from factory build list , but leaves sACU build presets (rambo sACU , engineer , shield etc). The presets work in this case , built sACU's can have all their upgrades built manually.
> 3) Restrictions on ACU's dont seem to work at all, except for teleporter.
> 4) When trying to restrict RAS on sACU's, while not restricting it on ACU's, lobby client checks both RAS'es , ACU and sACU. As mentioned above this not makes difference , restrictions not really work.

**Comment by HUSSAR-mtrela** [comment] 2016-08-14 20:49
1. Not an issue because adding restriction of RAS upgrade when sACU (RAS preset) is selected would add another complexity layer to the restriction system because what should happen to Rambo preset when a user restricts Combatant preset or some other combination of sACU presets that have similar/subset upgrades? 
2. Not an issue because sACU presets are separate units from the normal sACU and thus they are processed as separate units by the restrictions system. Although, I could add logic to restrict sACU presets when normal sACU is restricted but again that would add complexity to restriction system 
3. Not an issue because I cannot re-produce it either in release FAF patch or beta patch. Probably the user was restricting sACU upgrades and thought they were for ACU. Restricting only upgrades (e.g. RAS) that are shared between sACU and ACUs will be disabled on both units.
4. Not an issue because I cannot re-produce it either in release FAF patch or beta patch.

Potential issue is only with restricting sACU upgrade that is used to enhance sACU preset. I that scenario the game should also restrict that sACU preset. At  this moment the restriction system is not doing it but I could add support for it.

@aeoncleanse what do you think about it?

**Comment by aeoncleanse** [comment] 2016-08-15 13:43
I'll need to think about it. My real opinion though, as it has been for two years, is that the presets implementation is dumb, stupid, causes more headaches than its worth, and needs to be totally re-approached.

**Comment by MrRowey** [comment] 2022-05-23 12:07
Closing this isssue as it not a Currnt issuse that people are having and it the system works as intended

**Closed by MrRowey** 2022-05-23 12:07 UTC
Labels: area: sim, priority: low, area: unit-restrictions
