### ISSUE TITLE
Unitview crashes with options.gui_enhanced_unitview  == 0

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#764] opened 2015-07-13 23:54 UTC
Unitview crashes when "Single Unit Selected Info" is off. Line 168 in lua/ui/controls/worldview.lua checks for the option. 

Has something to do with unitviewDetail.View not being initialized. 

Have to sleep now though so feel free to check it out

**Comment by CodingSquirrel** [comment] 2015-07-14 02:29
Fixing this and #742 will likely be one and the same.

**Comment by Sheeo** [comment] 2015-07-14 10:32
Closed as duplicate of #742.

**Closed by Sheeo** 2015-07-14 10:32 UTC
Labels: bug, duplicate
