### ISSUE TITLE
emp medusa can stun ally tank

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1092] opened 2016-01-15 10:57 UTC
http://forums.faforever.com/forums/viewtopic.php?f=3&t=11356
(can't reproduct it)

**Comment by aeoncleanse** [comment] 2016-01-18 20:05
Asked for clarification if it's in beta or not. Currently uses 

'targets = self:GetAIBrain():GetUnitsAroundPoint(category, PosEntity or self:GetPosition(), buffTable.Radius, 'Enemy')'

**Comment by shalkya** [comment] 2016-01-18 20:26
it wasn't beta.

**Comment by duk3luk3** [comment] 2016-01-18 21:03
This is supreme commander, where allies get friendly fire'd and stunned. it's always been like that. imo not a bug if it's actually happening.

**Comment by aeoncleanse** [comment] 2016-01-18 21:17
If it's happening it's a bug because that command should only be fetching enemies, and 99% of the time medusa do not stun ally.

**Comment by shalkya** [comment] 2016-01-18 21:21
well i've no idea why this special time stun was working. (only stun since my unit weren't taking damage)

**Comment by MrRowey** [comment] 2021-11-23 21:34
@Garanas Just tested this could not recreate this issue so can be closed

**Comment by MrRowey** [comment] 2021-11-23 21:41
Tested with Direct fire onto a striker left it for 2 min and the stun effect was never applied. Issues must have been addressed in a future update

**Closed by MrRowey** 2021-11-23 21:41 UTC
Labels: status: need review
