### ISSUE TITLE
Infinite Error loop when spawning Engineer for Civ AI

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#180] opened 2014-12-13 20:39 UTC
WARNING: Error running '/lua/ui/game/gamemain.lua:OnBeat': c:\github\fa\lua\ui\uiutil.lua(358): attempt to concatenate local `filespec' (a nil value)
         stack traceback:
         	c:\github\fa\lua\ui\uiutil.lua(358): in function `UIFile'
         	c:\github\fa\lua\ui\game\avatars.lua(284): in function `Update'
         	c:\github\fa\lua\ui\game\avatars.lua(780): in function `v'
         	c:\github\fa\lua\ui\game\gamemain.lua(494): in function <c:\github\fa\lua\ui\game\gamemain.lua:492>

**Comment by ChrisKitching** [comment] 2015-06-28 07:56
Can't reproduce.

**Comment by aeoncleanse** [comment] 2015-06-28 08:32
Go on strip mine or any other map with civs.  Spawn that team an engie.

**Comment by aeoncleanse** [comment] 2015-06-29 15:39
This is the error:

WARNING: Error running '/lua/ui/game/gamemain.lua:OnBeat': e:\github\fa\lua\ui\uiutil.lua(338): attempt to concatenate local `filespec' (a nil value)
         stack traceback:
         	e:\github\fa\lua\ui\uiutil.lua(338): in function `UIFile'
         	e:\github\fa\lua\ui\game\avatars.lua(284): in function `Update'
         	e:\github\fa\lua\ui\game\avatars.lua(780): in function `v'
         	e:\github\fa\lua\ui\game\gamemain.lua(519): in function <e:\github\fa\lua\ui\game\gamemain.lua:517>

That was from the most recent build of release/3641. Clearly it's moved, but it's still here!

**Comment by Sheeo** [comment] 2015-06-29 16:46
Reproduced successfully from documented STR

**Comment by speed2CZ** [comment] 2016-04-09 09:19
Fixed long time ago ^^ closing

**Closed by speed2CZ** 2016-04-09 09:19 UTC
Labels: bug
