### ISSUE TITLE
AI not finishing builds on Blasted Rock

### ISSUE THREAD

**Issue by S7R7RPR** [FAForever/fa#3282] opened 2021-05-12 01:17 UTC
Been a long time user of FAF and discovered a weird bug on Blasted Rock. Played against AIX and SorianAIX with the same issues. The commanders did some really weird things and then watching the replay I saw the commander starting a lot of builds and then just not finishing them. Not sure if it's addressable but figured I might as well report it!

https://replay.faforever.com/14493966
https://replay.faforever.com/14493990

**Comment by Uveso** [comment] 2021-05-12 16:50
Both games desync, so maybe i did not see how it was in reality;

1st game, UEF AI ACU left the factory building to attack the middle of the map
2nd game, both AI ACUs are interrupting the build because of enemy threat.
(The ACU should attack in this situation and not continue to build; One unfinished building would be normal)

Sadly i can't reproduce the error on my PC.
Blasted Rock is one of my AI test maps and i played hundreds of AI games on it.

Do me a favor; please install my AI mod and try the map again.
(My AI has extended debug function to trace down any AI errors)

https://forum.faforever.com/topic/350/

**Comment by S7R7RPR** [comment] 2021-05-13 00:16
Alright so I tried again on my own with both AIs and they performed more or less the same
https://replay.faforever.com/14499998

I then downloaded your AI from the vault and ran with that and the AI performed much much better.
https://replay.faforever.com/14500060

Based on the behavior comparison, I'm going to hazard a guess that it was a resource based bug. In the second game, I noticed the commanders kept just chilling and not doing anything for a bit. They started a few builds and moved on, but not nearly as many as before.

**Comment by Uveso** [comment] 2021-05-13 05:22
I was able to reproduce the error where the ACU was doing nothing.
It turned out that there was a small error inside the `ProcessBuildCommand` function.

I added a gamepatch to my AI and fixed the `ProcessBuildCommand`.
You can test it if you like. Just download and enable my develop AI mod.
You don't need to play against AI-Uveso, its also working for Sorian and GPG AI.

Please have in mind, this is a develop version of my AI, don't play it online!
[AI-Uveso-Mod-S7R7RPR.zip](https://github.com/FAForever/fa/files/6470467/AI-Uveso-Mod-S7R7RPR.zip)

In case you are interested in AI development, support or just information, join us on our AI developer Discord:
https://discord.gg/ChRfhB3

**Comment by Garanas** [comment] 2022-05-07 09:31
Closing this issue - @Uveso can you make a pull request to the repository with the changes you made to your mod to fix this?

**Closed by Garanas** 2022-05-07 09:31 UTC
Labels: area: AI

**Comment by Uveso** [comment] 2022-05-07 13:37
sure, i will make the PR tomorrow.
