### ISSUE TITLE
Nuke and SMD pgen adjacency don't work if you build the pgens after

### ISSUE THREAD

**Issue by ChessBerry** [FAForever/fa#3641] opened 2022-01-03 09:12 UTC
Building pgens adjacent to an SMD/nuke should reduce its power consumption but doesn't. Moon and me noticed it in this game: 16042407 and I was able to easily reproduce it in this sandbox: 16044635.

Strangely, if you build an SMD/nuke next to already existing pgens, the adjacency bonus does work correctly, but if you build the SMD/nuke first and then the adjacent pgens after, it doesn't. See the sandbox here: 16044694

My very quick tests of some other power adjacencies weren't able to find a problem anywhere else. Most notably (air-)factories and omnis aren't affected by whatever weirdness is going on here.

**Comment by Garanas** [comment] 2022-01-03 09:26
Stop breaking the game Cheese.

**Comment by ChessBerry** [comment] 2022-01-03 09:26
Never!

**Comment by speed2CZ** [comment] 2022-01-03 12:41
Duplicate of https://github.com/FAForever/fa/issues/1843

**Comment by Garanas** [comment] 2022-01-03 14:32
What if we'd use the dummy build drone used to gift unfinished experimental units to reset the missile builder when an adjacency change is detected? We could cancel it, restart it and boost it.

**Comment by Garanas** [comment] 2022-08-05 21:17
I've tried experimenting, solving this issue.

```lua
        LOG("AdjustAdjacencyToMissileConstructionThread")

        LOG(self.Blueprint.BlueprintId)
        reprsl(self.Blueprint.General)
        LOG(self.Blueprint.General.CommandCaps.RULEUCC_SiloBuildTactical)
        LOG(self.Blueprint.General.CommandCaps.RULEUCC_SiloBuildNuke)

        LOG(self:SetWorkProgress(0.95))

        local px, py, pz = self:GetPositionXYZ()
        local test = CreateUnitHPR('url0309', self.Army, px+5, py, pz, 0, 0, 0)
        IssueGuard({test}, self)
        self:StopSiloBuild()
        IssueSiloBuildTactical({self})
        self:SetAutoMode(true)
        self:SetBuildRate(4180) -- set crazy build rate and consumption = 0
        self:SetProductionPerSecondEnergy(60)
        self:SetProductionPerSecondMass(6000)

        WaitTicks(10) -- wait some ticks (3 is minimum), IssueBuildMobile() is not instant
        self:SetBuildRate(1080) -- set crazy build rate and consumption = 0
        self:SetProductionPerSecondEnergy(0)
        self:SetProductionPerSecondMass(0)

        local count = 10
        while count > 0 do

            LOG(self:GetWorkProgress())
            LOG(self:GetConsumptionPerSecondEnergy())
            LOG(self:GetConsumptionPerSecondMass())
            LOG(self:GetResourceConsumed())
            LOG(self:GetProductionPerSecondEnergy())
            LOG(self:GetProductionPerSecondMass())


            WaitSeconds(1.0)
            count = count - 1
        end
```

I'm afraid that there is no feasible solution. At best we can restart creating the missile and try and make up for the loss, but if the player is stalling while we try doing so then it is anything but smooth and the player likely loses a lot of progress.

Using `unit:SetWorkProgress()` also doesn't work, as it appears to be reset again (to the old value) the next tick.

It appears that this is something we can't beat, for now. I'm closing this issue as not planned - it is the way it is.

**Closed** 2023-06-10 16:49 UTC
Labels: area: sim, priority: medium
