### ISSUE TITLE
need to fire chrono dampner on land to fire it afterward in water

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2410] opened 2018-03-15 10:31 UTC
can't be really more precise... i will try to show you different example : 
1st : be in water, get opponent land/navy around you =>chrono dampner doesn't work.
2nd : be on the ground, fire chrono dampner, get in water, chrono dampner keep on working.
3rd : lose the range on unit (land or navy) while being water, get back in range, still in water => chrono dampner doesn't work.

i guess it is triggered by the fact that it can't fire his primary weapon under water or something like that?
[game.uid.7630337.log](https://github.com/FAForever/fa/files/1814935/game.uid.7630337.log)
content.faforever.com/faf/vault/replay_vault/replay.php?id=7630337

**Comment by Ithilis** [comment] 2019-10-27 11:04
Same problem with air. 
there is easy solution, change weapon firing pattern where it will look also for AIR/NAVAL units.

**Comment by Garanas** [comment] 2022-08-11 09:52
If someone manages to sandbox this in a more recent version of the game 👍

**Comment by lL1l1** [comment] 2024-05-01 01:10
From #5883:

> To replicate the issue, start chrono with targeting of a land/sea surface unit, then walk underwater while staying within its 35 range. It will stay locked on and never check its own inability to fire underwater, so it'll keep firing underwater.
This is caused by its custom firing cycle that never goes to the OnFire event except in the initial target acquisition. The cycle:
`idle -> FireReady -(FireReady.OnFire)-> FiringState (repeat forever) -(FiringState.OnLostTarget)-> Idle`

Practically fixed by allowing it to fire underwater, but technically it is not fixed and any Chrono dampener weapon that can stun units on a certain layer without being able to fire to that layer from its own layer will have that bug.

**Closed** 2024-05-30 08:47 UTC
