### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by marvin4ward** [FAForever/fa#3235] opened 2020-12-10 05:19 UTC
If this make sense to develop, please LMK, I will improve issue according to rules.

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0067aa5f
    attempted to read memory at 0x00000000

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_13337211.log /replay C:\ProgramData\FAForever\cache\temp.scfareplay /replayid 13337211

Callstack:
	Unknown symbol (address 0x0067aa5f)

Last 100 lines of log...

info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: SSB >>> TRACE Sync.FocusArmyChanged -1
debug: Loading module '\000/projectiles/saaolarisaaartillery03/saaolarisaaartillery03_script.lua\000'
info: CWldSession::DoBeat() unknown entity id (0x2ff0060c) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff0060d) supplied in a pose update.
debug: Loading module '\000/projectiles/sifhuantinuke01/sifhuantinuke01_script.lua\000'
debug: Loading module '\000/effects/entities/sifhuantinuke02/sifhuantinuke02_script.lua\000'
debug: Loading module '\000/effects/entities/sifhuantinuke03/sifhuantinuke03_script.lua\000'
debug: Current gametime: 00:58:30
info: CWldSession::DoBeat() unknown entity id (0x2ff0033c) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff00372) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff00586) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff00044) supplied in a pose update.
debug: Loading module '\000/projectiles/aifquantumwarhead02/aifquantumwarhead02_script.lua\000'
debug: Loading module '\000/effects/quantumwarhead/quantumwarheadeffect01_script.lua\000'
info: CWldSession::DoBeat() unknown entity id (0x2ff003bc) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff00410) supplied in a pose update.
debug: Current gametime: 00:59:00
info: CWldSession::DoBeat() unknown entity id (0x2ff00269) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff0019c) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff001cc) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff001e2) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff00206) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff0042c) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff00455) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff00269) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff0049d) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff00508) supplied in a pose update.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
debug: Loading module '\000/units/zsb9601/zsb9601_script.lua\000'
info: CWldSession::DoBeat() unknown entity id (0x2ff00182) supplied in a pose update.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
debug: Current gametime: 00:59:30
info: CWldSession::DoBeat() unknown entity id (0x2ff002d6) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff004c1) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff00625) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff0063c) supplied in a pose update.
debug: Loading module '\000/units/xab1401/xab1401_script.lua\000'
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
debug: Current gametime: 01:00:00
debug: Loading module '\000/units/xsl0402/xsl0402_script.lua\000'
debug: Loading module '\000/units/xsb2302/xsb2302_script.lua\000'
info: CWldSession::DoBeat() unknown entity id (0x2ff004fd) supplied in a pose update.
debug: Current gametime: 01:00:30
info: SetFocusArmy 0
info: syncing max ping markers: \00015
info: SSB >>> TRACE Sync.FocusArmyChanged 1
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
info: *FORMATION DEBUG: Unit "urs0304" does not match any Naval categories.
debug: Current gametime: 01:01:00
debug: Current gametime: 01:01:30
info: CWldSession::DoBeat() unknown entity id (0x2ff00235) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff0046b) supplied in a pose update.
info: SetFocusArmy -1
info: syncing max ping markers: \00015
info: Sending game result: 5 defeat -10
info: SSB >>> TRACE GameResults: result = defeat -10, armyID = 5, name = Dobrii-Korjik
info: SSB >>> TRACE GameResults: Dobrii-Korjik has been defeated by Dobrii-Korjik
info: SSB >>> TRACE AnnounceDeath Dobrii-Korjik  has been defeated by  Dobrii-Korjik
info: SSB >>> TRACE OnBeat() player has died: Dobrii-Korjik
info: SSB >>> TRACE Sync.FocusArmyChanged -1
debug: Current gametime: 01:02:00
info: Sending game result: 1 defeat -10
info: SSB >>> TRACE GameResults: result = defeat -10, armyID = 1, name = Firv
info: SSB >>> TRACE GameResults: Firv has been defeated by Firv
info: SSB >>> TRACE AnnounceDeath Firv  has been defeated by  Firv
info: SSB >>> TRACE OnBeat() player has died: Firv
info: CWldSession::DoBeat() unknown entity id (0x2ff0041c) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff00451) supplied in a pose update.
info: SSB >>> TRACE AnnounceUnit captn_JL HAS BUILT AN EXPERIMENTAL UNIT!
info: CWldSession::DoBeat() unknown entity id (0x2ff00504) supplied in a pose update.
info: Block is too late ! 
info: terminated 
info: SSB >>> TRACE AnnounceUnit TwentyEight HAS BUILT AN EXPERIMENTAL UNIT!
debug: Current gametime: 01:02:30
debug: Loading module '\000/projectiles/sifsuthanusartilleryshell02/sifsuthanusartilleryshell02_script.lua\000'
info: Sending game result: 7 defeat -10
info: SSB >>> TRACE GameResults: result = defeat -10, armyID = 7, name = trigered_g1pos
info: SSB >>> TRACE GameResults: trigered_g1pos has been defeated by trigered_g1pos
info: SSB >>> TRACE AnnounceDeath trigered_g1pos  has been defeated by  trigered_g1pos
info: SSB >>> TRACE OnBeat() player has died: trigered_g1pos

**Comment by KionX** [comment] 2020-12-10 09:08
Game crashes may occur due to lack of memory, hardware problems, or problems with third-party software.
If the game crashes, replays are useless. They do not save events that lead to a crash.
In my experience, the game is stable. And such reports are useless to consider.

**Comment by KionX** [comment] 2020-12-10 09:31
As far as I understand, the crash occurred when trying to read the type of collision of the unit. I have no idea what this is about.

**Comment by marvin4ward** [comment] 2020-12-11 02:19
> If the game crashes, replays are useless. They do not save events that lead to a crash.
So if the game crashes on replay it does not help anyhow? I tried on replay downloaded from the server, and got same result on two PCs. So seems it reproducable. I will try find other players to clarify their experience. If they had no issues, I will close this issue.

PS Thank you for prompt answer.

**Comment by KionX** [comment] 2020-12-11 06:48
In this replay, the crash is reproduced.

**Comment by KionX** [comment] 2020-12-11 08:02
Similar issue https://github.com/FAForever/fa/issues/318
This seems to be the problem: ```SetCollisionShape('None')```

**Comment by KionX** [comment] 2020-12-11 13:55
When trigger_g1pos is defeated, the ura0001 collision is "None" and this causes a crash.

**Comment by KionX** [comment] 2020-12-14 11:41
I've completed crash research. Similar issue #318
Crash occurred when trying to read the type of collision of the unit.
When trigger_g1pos is defeated, the ura0001 collision set to "None" and this causes a crash.
The collision was removed in this line:
https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/SimUtils.lua#L399
Similar problems occur with other air units.
RevertCollisionShape has not been called.
This is probably because KillArmy was called asynchronously:
https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/aibrain.lua#L717

**Comment by Garanas** [comment] 2021-09-01 10:11
We'll need to make a call here @Tagada14 as to what the best approach is.

The issue is that setting the collision box to 'None' for units makes the game unstable and allows it to hard-crash. When I was experimenting with the Cybran drones I tried to do the same thing: game hard-crashed after ~ 5 - 10 seconds with a null reference exception (that is what is happening here too).

The issue it is trying to solve is preventing wrecks and / or units from interfering with rebuilding an unfinished unit that we're trying to automatically gift after we've died. This means that the code is critical for the current balance. As far as I can think of it, there's four things we can do:
 - (1) We do not allow unfinished buildings to be gifted and create a typical wreck.
 - (2) We do not allow unfinished buildings to be gifted and create a wreck that allows you to start where it was previously.
 - (3) We allow unfinished buildings to be gifted at the cost of temporarily warping all units / wreckages in the building skirt to another location. It requires a few ticks for the dummy builder to start rebuilding the structure - this means the units / wrecks will be warped off temporarily.
 - (4) We allow unfinished buildings to be gifted at the cost of spawning in the wreck / units that block such a building a few ticks after all the other units have been gifted. This allows the dummy builder to initiate the constructing.

From a development perspective my preference is (1), but I understand that may not be desirable. I'll leave the call to you and the balance team.

**Comment by KionX** [comment] 2021-09-01 10:33
In my experiments, I was able to change the owner of a unit without re-creating it. But I haven't studied the long-term effects.
As I understood in FAF, it is impossible to complete the construction of a unit immediately.
As far as I remember, null collisions are allowed for ground units.
Perhaps some engine improvements can help.

**Comment by Garanas** [comment] 2021-09-01 11:45
If you can make it stable then cybran build drones become essentially free of charge 😄

**Comment by KionX** [comment] 2021-09-02 11:03
I managed to disable a large piece of code that doesn't seem to do anything useful.
This solves the problem with 'None' collisions.
However, it affects the sim.
This code works while the unit is in the air.
I checked the UEF air units and the Cybran engineer.
![](https://user-images.githubusercontent.com/5648030/131831370-dd9ca9cb-e2ec-4b4b-a3cf-a5c6eedbf150.png)
On the left are units that are not affected by the code.
On the right, this causes an early OnLayerChange. Why?

**Comment by marvin4ward** [comment] 2021-09-03 03:57
Thank you for looking into.

**Comment by Crotalus** [comment] 2021-09-16 20:43
All units to the right have transport ability so I guess they use an OnLayerChange event to trigger something. 

Could the crash have something to do with setting collision shape on dead / destroyed  wrecks? After a WaitTicks() wrecks could have been destroyed / recycled by the game.

**Comment by KionX** [comment] 2021-09-17 10:45
_All units to the right have transport ability_
There is also a scout.
I checked the behavior of the transport. I didn't notice any changes.

_Could the crash have something to do with setting collision shape on dead / destroyed wrecks?_
The problematic code only works when air are landing.

**Comment by KionX** [comment] 2021-09-17 14:59
An interesting feature is that units do not collide with units without a collision.
But units without a collision collide with units with a collision.

**Comment by Garanas** [comment] 2022-05-07 09:32
Closing this issue as it has dated and it is fixed in game version 3737.

**Closed by Garanas** 2022-05-07 09:32 UTC
Labels: type: bug, area: sim, type: core dump
