### ISSUE TITLE
Mousing over an unselected unit does not cause the unit-detail-view to appear

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#742] opened 2015-07-10 23:10 UTC

**Comment by CodingSquirrel** [comment] 2015-07-11 03:19
I'm not able to reproduce this issue. If I have no unit selected and I hover over a unit the detail window shows up. If I select one unit and then hover over another unit that other units details show up until I mouse off of it. Can you give some steps to reproduce?

**Comment by Sheeo** [comment] 2015-07-11 09:59
I believe this was resolved in #741. #743 is a byproduct.

**Comment by ChrisKitching** [comment] 2015-07-13 08:20
I'm apparently not the only one:
http://forums.faforever.com/forums/viewtopic.php?f=3&t=10271

**Comment by CodingSquirrel** [comment] 2015-07-13 13:13
I still can't reproduce this. Can I get a more detailed description of what's happening?

**Comment by CodingSquirrel** [comment] 2015-07-14 02:28
It looks to me like this issue stems from 07fa8b84b7c6ae4ce8284c0cc42dcecb2c9ec3de and I'm not quite sure what the benefit we're gaining from it is. Basically it just moves the check for rollover from every frame to every time you move your mouse. While this creates a better best case scenario, I'd imagine most people while playing don't hold their mouse still for very long, so you're not going to get much benefit from decreased checks from the mouse being held still. But it has a much worse worst case scenario, since the handler function for mouse movement can be called *significantly* more frequently than a frame tick.

I'm thinking I'm going to just revert this, mostly. I like having the selection saved from OnSelection instead of checking that each frame though.

**Comment by CodingSquirrel** [comment] 2015-07-14 03:40
Added pull request #765 with a fix for this.

**Comment by Sheeo** [comment] 2015-07-29 14:18
This has been fixed with merge of #765.

**Closed by Sheeo** 2015-07-29 14:18 UTC
Labels: bug, high, regression, ui
