### ISSUE TITLE
Integrate Advanced Reclaim Info 

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3539] opened 2021-11-12 10:52 UTC
A requirement for the optimizations of reclaim labels to function. The mod in question hard-hooks the inefficient function.

**Comment by HUSSAR-mtrela** [comment] 2022-05-08 17:14
this issue looks like a duplicate of issue #1631 - Cluster reclaim labels

**Comment by 4z0t** [comment] 2023-02-12 23:42
After refactoring of reclaim labels, do we even need it?

**Comment by Garanas** [comment] 2023-02-13 06:54
People still want it 😄

**Comment by MrRowey** [comment] 2023-02-24 16:43
This is different to Reclaim labels allows you at a quick glance to see the total mass visible on the screen

**Comment by MrRowey** [comment] 2024-06-19 20:19
it been a while since this was removed san people are gotten used to being with out it

**Closed by MrRowey** 2024-06-19 20:19 UTC
Labels: area: ui
