### ISSUE TITLE
Launch failed in every automatch.

### ISSUE THREAD

**Issue by andrew228322** [FAForever/fa#3694] opened 2022-03-11 10:11 UTC
**Describe the bug**
A clear and concise description of what the bug is. Do not forget to append the game logs.

**To Reproduce**
A clear and concise set of instructions on how to reproduce the issue. Best accompanied with a sandboxed replay. An in-action replay is helpful but not sufficient - the burden to investigate how to reproduce the issue is then moved to the maintainer.

**Expected behavior**

**Screenshots**

**Additional context**

_This bug report will be read by people that have not experienced the bug themselves - this report is all they have to investigate. The more precise your report, the easier it becomes for us to help you._

**Comment by andrew228322** [comment] 2022-03-11 10:15
Custom game start well. 
Sometime I can play, there log of sucesful starting and ending. But after this game the error repeated.
Good game: [https://forum.faforever.com/assets/uploads/files/1646936983710-game_16526550.log](url)
Failed launch after this game: [https://forum.faforever.com/assets/uploads/files/1646936989571-game_16526890.log](url)
Ice adapter log: https://forum.faforever.com/assets/uploads/files/1646937361623-ice-adapter.log

**Comment by Garanas** [comment] 2022-03-11 10:53
It feels to me this issue is in the wrong repository, but I do understand the frustration. @BlackYps if I recall then changes are in the make to tackle issues with the matchmaker, does one of them solve this?

**Comment by BlackYps** [comment] 2022-03-11 13:04
It depends on what exactly caused the failed launches. There is a bug in the ICE adapter that causes connection problems sometimes. Geosearchef is working on a fix, but we don't know when it will be ready. It could also be that other players aborted the game, because they didn't like the map. The planned feature to automatically ban people for a short time from matchmaking if they dodge matches will address this and be available in the near future.
I can't really comment on what the cause is in your particular case. Chances are that you just got unlucky with your latest attempts as in general people are able to play in the matchmaker.

**Comment by andrew228322** [comment] 2022-03-11 13:13
> It depends on what exactly caused the failed launches. There is a bug in the ICE adapter that causes connection problems sometimes. Geosearchef is working on a fix, but we don't know when it will be ready. It could also be that other players aborted the game, because they didn't like the map. The planned feature to automatically ban people for a short time from matchmaking if they dodge matches will address this and be available in the near future. I can't really comment on what the cause is in your particular case. Chances are that you just got unlucky with your latest attempts as in general people are able to play in the matchmaker.

Understood, big thaks

**Comment by Garanas** [comment] 2022-03-11 13:27
With that, I'll close this issue.

**Closed by Garanas** 2022-03-11 13:27 UTC
Labels: status: novel issue

**Comment by andrew228322** [comment] 2022-03-11 13:36
a
