### ISSUE TITLE
UEF TMD stops firing

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#404] opened 2015-01-22 12:56 UTC
Replay ID 3013192

**Comment by aeoncleanse** [comment] 2015-01-22 13:03
For reference, this is the only change to the weapon in the mod.

UnitBlueprint {
    Merge = true,
	BlueprintId = "ueb4201",						#UEF TMD
    Weapon = {
        {
            TargetCheckInterval = 0.1,
            TrackingRadius = 1.1,
        },
    },
}

UEF TMD is the only one which is projectile-based, and the reason it is the worst is because it seriously overkills incoming threats, and can also miss. These changes cut the overkill and no-fire down a lot by forcing each one to target check every tick, meaning no more stupid pauses. The TrackingRadius reduction means that packed TMD will not overkill so much because they all locked onto one projectile when it was further out, then don't target check in time.

Neither of these can possibly be causing this issue.

**Comment by aeoncleanse** [comment] 2015-01-22 14:25
This is absolutely dead-end, there is NOTHING in the log at all, not even with full debugging turned on.

**Comment by Sheeo** [comment] 2015-01-22 14:31
Why do you expect something to be in the log?

**Comment by aeoncleanse** [comment] 2015-01-22 15:32
Because the log is my friend? ;) I can't even begin to imagine what might be causing this though, it's almost as if the TMD has some kind of ammo...

**Comment by ChrisKitching** [comment] 2015-01-22 17:46
> Because the log is my friend? ;) I can't even begin to imagine what might be causing this though, it's almost as if the TMD has some kind of ammo...

It's debugging time!

Since it's a pain in the backside to reproduce this bug, my suggestion is that you add excessively verbose loggging to the code controlling the TMD, reproduce the bug, and see what's different.
This should, at least, point you in the right direction.

**Comment by aeoncleanse** [comment] 2015-01-22 19:19
That's the thing, the code controlling the TMD is almost completely default. There's no modification other than some spinup FX which just... can't... be causing this. Not without throwing a tantrum in the log...

How do I get a replay to launch my git branch?

**Comment by Sheeo** [comment] 2015-04-10 00:55
Sorry, I never got back to you on this.

Launching replays using modified code requires a bit of hacking at the moment -- it's something I'd like to be able to do easily with the client update.

**Comment by DeimosEvotec** [comment] 2015-08-25 15:39
So, anybody still interrested in this?
I can reproduce this bug with nearly all units that shoot tacs in this replay id 3798200

**Comment by aeoncleanse** [comment] 2015-09-13 02:10
Interested, sure, just nobody is any more clued up on wtf could be causing this

**Comment by Crotalus** [comment] 2015-09-13 06:33
Seems like the aim controller gets confused when there is several missiles at once. The weapon is stuck in RackSalvoFireReadyState so maybe add some sanity check there with:
`self:HasTarget() and not self:CanFire()`

Can be unlocked with `SetHeadingPitch` to some sane value, another option would be `SetResetPoseTime()` (currently 99999 for all structures). A problem is that as long as the missiles are flying the TMD never reset goes into "reset pose" mode

**Comment by shalkya** [comment] 2016-01-18 14:49
maybe it's link to this : http://forums.faforever.com/forums/viewtopic.php?f=3&t=10631

i couldn't reproduce it in beta.

**Comment by DeimosEvotec** [comment] 2016-01-18 18:34
Nope, it's just hard to reproduce but it's still there. Tested it and I still got it by firing missiles in a very high arc above it, forcing it to fire straight up either with 2hp missiles or just through volume of fire.

**Comment by Garanas** [comment] 2021-09-08 11:51
This issue has aged and the replay is no longer available in the vault. I am closing this issue.

**Closed by Garanas** 2021-09-08 11:51 UTC
Labels: type: bug, area: sim
