### ISSUE TITLE
Observers are sometimes not shown in the Lobby

### ISSUE THREAD

**Issue by OCGDFS** [FAForever/fa#378] opened 2015-01-16 21:36 UTC
Observers are sometimes not shown in the lobbyfor some time, even though they are there, and causing connection problems to players. The problem is that I arent able to kick them, and start the game.

**Comment by Sheeo** [comment] 2015-01-17 01:23
Thanks for the report.

I'm thinking this is a potential duplicate of #322 and #377, or there is at least a strong correlation between these issues.

**Closed** 2015-01-21 19:47 UTC
