### ISSUE TITLE
Teleport Buildorders does not work in current patch(3661)(works in Beta)

### ISSUE THREAD

**Issue by Androish** [FAForever/fa#1659] opened 2016-11-02 20:46 UTC
![telebuildorder](https://cloud.githubusercontent.com/assets/16946169/19946553/c767efae-a144-11e6-8f1a-ee83c56b7b28.png)

Before this patch you could que buildorders after teleport command, You still can, but it gets "stuck" because the tele command does not dissapear after teleport. If you manually remove that command it will go on.

I tried without UI mods same result.

It works in FAF Beta (3662) Tested

**Comment by aeoncleanse** [comment] 2016-11-02 20:49
It possible this was already fixed with this: https://github.com/FAForever/fa/pull/1657

When you say it works in beta, do you mean it bugs out in beta, or works as intended? Just so I'm 110% clear :)

**Comment by Androish** [comment] 2016-11-02 20:52
It works as intended in beta. Funny how it (possibly) got broken and fixed without any devs noticing it was broken :D

**Comment by aeoncleanse** [comment] 2016-11-02 20:55
The  thing that broke was aesthetically motivated rather than functional. I made the connection only because it caused the tele exit script to crash, which would _probably_ cause this :)

**Comment by Androish** [comment] 2016-11-02 20:58
Now I'm just hoping it will be merged soon :)  In some games(really big maps) It's nice to teleport all around the place with a long buildorder Having to manually start it at every location is not that great :P

**Closed** 2016-12-21 19:09 UTC
