### ISSUE TITLE
Balance Mod 

### ISSUE THREAD

**Issue by Sir-Prize** [FAForever/fa#383] opened 2015-01-20 15:07 UTC
Hi all

I've been talking to IceDreamer about the balance mod for the next patch, so we can run some tournaments and get some info. I think the mod is close to ready, at the moment the main issue I've seen is there's a UEF TMD rebalance, and at the moment the TMD appears to give up shooting at missiles after a while, for example in replay ID 2986448. The last time I tested it I got a 4.5MB log, which can be downloaded here: https://www.dropbox.com/s/3whmwnv7j4o09f5/game%20%285%29.log?dl=0

Watch at +10, after a while the TMD just stops caring, around the 14 minute mark.

Is there any scope for adding in the Torp Bomber and Viper rebalance as well? The balance mod is currently in the vault, it's "balancepreview".

**Comment by aeoncleanse** [comment] 2015-01-21 16:59
Could just have asked me ;) Do you want Torps and Viper in too?

There's no way in hell the mod broke the TMD, it's barely touched and it's just a simple bp adjustment.

**Comment by Sir-Prize** [comment] 2015-01-21 22:31
Yeah I asked you what the changes were in the pm and now I know I think we should test them. So I'm asking here :) I just figured it made more sense to have our conversation here than forum pm. 

I have only had the log issue I had once, that replay when testing tmd. I'll see if I can replicate but yes I suspect it is fine. The TMD switching off after a while is an issue though, surely?

**Comment by aeoncleanse** [comment] 2015-01-21 22:59
Nope, because A: My changes can't be causing it and B: You're using a billion mods, making debugging impossible.

This is the error causing the huge log:
warning: Error running '/lua/ui/game/gamemain.lua:OnBeat': ...ramdata\faforever\gamedata\lua.nx2\lua\ui\uiutil.lua(323): attempt to concatenate local `filespec' (a nil value)
         stack traceback:
         	...ramdata\faforever\gamedata\lua.nx2\lua\ui\uiutil.lua(323): in function `UIFile'
         	...a\faforever\gamedata\lua.nx2\lua\ui\game\avatars.lua(284): in function `Update'
         	...a\faforever\gamedata\lua.nx2\lua\ui\game\avatars.lua(780): in function `v'
         	...\faforever\gamedata\lua.nx2\lua\ui\game\gamemain.lua(503): in function <...\faforever\gamedata\lua.nx2\lua\ui\game\gamemain.lua:501>

**Comment by Sir-Prize** [comment] 2015-01-21 23:17
You're not speaking to someone with much background in programming so bear that in mind: why are ui mods likely to cause a tmd to stop firing?

**Comment by Sheeo** [comment] 2015-01-21 23:23
Seems rather unlikely that a UI mod would unprovoked sim behavior changes.

We may well be looking at a compatibility thing caused by the way the balance mod is loaded...

**Comment by aeoncleanse** [comment] 2015-01-21 23:25
It's unlikely whatever the cause, but AFAIK there's no way it's the actual change to the unit. It's just a basic rule of testing that you never have any mod enabled other than the one you're testing out.

Sheeo, any clue on that error? Does concatenate have something to do with the ..stuffhere.. thingy?

**Comment by Sheeo** [comment] 2015-01-21 23:32
Yes it's compatibility problems with the UI changes in 3639.

UI mods can be safely kept enabled during testing of sim mods, simply because of the good seperation of concerns between the code. Of course this does not hold if you are testing UI changes, however.

**Comment by Sir-Prize** [comment] 2015-01-22 12:04
Well in replay 3013216 I broke UEF TMD with absolutely no mods active. All other factions worked fine. When I tested with only my UI mods active nothing broke in replay ID 3013192.

So it's not the balance mod, it's just a bug.

**Comment by Sheeo** [comment] 2015-01-22 12:56
Let's spin out a new issue for this oddity, then! Good job @Sir-Prize :)

**Comment by ChrisKitching** [comment] 2015-01-26 05:15
#404 is now tracking the TMD bug. All done here, methinks?

**Comment by Sir-Prize** [comment] 2015-01-28 06:14
So there's one final issue actually, which I should have mentioned in the OP. Split build doesn't ALWAYS work, while split move and split overcharge do. Here's my game.log for replay ID 3032351:

https://www.dropbox.com/s/yw99m0m21llbw5f/game%20%286%29.log?dl=0

As I say in chat, it appears if it's combined with a move order, split build can work, but if you just order two engineers to go make a wall immediately without queuing anything else, you get them behaving like there's no mod. This feature worked in the mod "3637 preview v6", so it might be possible to use code from that?

Thanks again for your help Ice and others.

**Comment by Sir-Prize** [comment] 2015-02-02 10:41
Hey guys

Any idea if this is something that can be (or should be, given the effort that might be needed) tackled for this mod? If it's one of these things that basically doesn't quite work due to mod code, I'm kind of tempted to just forget it and just get on with testing tournaments and hosted games. Not sure if the suggestion to look at the last mod helps or not.

**Comment by Sheeo** [comment] 2015-02-02 11:01
Hey Sir-Prize, the mod-version of the balance mod is obsolete at this point.

We've got quite a few improvements waiting for merge since then, so I say we go move 3641 to a release branch (Feature freeze) during today and develop can start being 3642.

**Comment by aeoncleanse** [comment] 2015-02-02 15:08
Sheeo I've been keeping the mod up-to-date. The thing is, split-build isn't working for him or something, but it works perfectly for me every time I try to debug it...

**Comment by Sir-Prize** [comment] 2015-02-04 13:11
Can someone other than Ice have a go at trying to use/break split build with the balancepreview mod?

**Comment by Sir-Prize** [comment] 2015-02-06 13:28
My clanmates tested this - and some other stuff - replay ID 3061581.

**Comment by aeoncleanse** [comment] 2015-02-06 19:05
Interested in hearing more on rebuild + shields, not heard that one before. What about the rest of it, the change, many won't have been seen (Nukes, Billy etc) but general impressions?

**Comment by Sir-Prize** [comment] 2015-02-08 06:04
I didn't quite understand what they were saying, but it sounded like they were rebuilding ED5s for very cheap.

Overall, it sounded like split-build was still a little broken but it's a handy tool. Split-ground fire is now in there, someone was saying that would be OP for Zthuee vs subs (I disagree tbh, but that's the point of this mod, I will make people play on navy maps :)). People were happy the target bones were fixes too. 

On reclaim, which will almost certainly end up being the controversial thing, the idea to reprogram reclaim behaviour to be consistent across manual and automated orders came up instead of/at the same time as area reclaim.

**Comment by aeoncleanse** [comment] 2015-02-08 12:42
That last thing is what I really, really want to do, but without the engine code I'm afraid it's out of reach :(

**Comment by aeoncleanse** [comment] 2015-02-08 14:50
http://forums.faforever.com/forums/viewtopic.php?f=42&t=9379

**Comment by Sheeo** [comment] 2015-04-10 00:26
Closing this again, if we have more specific issues they should be opened anew

**Closed by Sheeo** 2015-04-10 00:26 UTC
