### ISSUE TITLE
Disable ambient sounds

### ISSUE THREAD

**Issue by Blodir** [FAForever/fa#4574] opened 2023-01-10 11:59 UTC
**Describe the feature**
Ambient sounds are really loud and bothersome. They distract from actually relevant sounds eg. bombers dropping, labs firing, etc.

**Expected behavior**
There should be a slider or a checkbox in the sound settings to change the volume of- or disable ambient sounds.

**Comment by Garanas** [comment] 2023-01-10 12:01
As discussed in Discord, I'm wondering if (not) playing sounds would cause a desync. I also do not understand why the sounds are so loud for you, I can barely hear them.

I'll look into making the sounds optional.

**Comment by speed2CZ** [comment] 2023-01-10 16:39
Are you sure it's just not bugged audio caused by incompatible windows settings? What sounds are you talking about?

**Comment by Garanas** [comment] 2023-02-13 07:03
I'm closing this - I've not found a way to make them optional. In particular weapon ambient sounds are attached to entities. Seems like a bug with your setup, as speed2 points out.

**Closed by Garanas** 2023-02-13 07:03 UTC
Labels: type: enhancement
