### ISSUE TITLE
Cybran T3 MAA spamming log with error when shooting

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#916] opened 2015-09-13 13:07 UTC
INFO: *ERROR: THERE IS NO INSTIGATOR FOR DAMAGE ON THIS COLLISIONBEAM = \000{
INFO:   CollideFriendly=false,
INFO:   DamageAmount=0,
INFO:   DamageFriendly=false,
INFO:   DamageRadius=0,
INFO:   DamageType="Normal"
INFO: }

**Comment by ppipp** [comment] 2015-09-13 13:39
It's due to the fact Ze Pilot didn't properly implement the unit, and didn't add some fx (the red tracking beam fx). It should be easy to fix this when looking at the files in the mod "t3 mobile AA" in the vault.

**Comment by duk3luk3** [comment] 2015-09-14 11:55
Duplicate of #883

**Closed by duk3luk3** 2015-09-14 11:55 UTC
