### ISSUE TITLE
Seraphim Transport loading

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#2521] opened 2018-07-13 13:59 UTC
Seraphim air transports load units poorly, the units don't get picked up from directly under the transport, they have to move a little past the transport. There's a lot of walking and bumping of units when trying to load, other transports load much easier and faster. It is especially problematic when there is an acu and/or buildings nearby.

**Comment by MrRowey** [comment] 2021-11-08 00:01
@Garanas im assuming this merged pr fixed this issues unless @Tagada14 this is something that need to be looked at in balance team

**Comment by Garanas** [comment] 2021-11-08 00:12
Tagada can close if it is considered solved.

**Comment by Tagada14** [comment] 2021-11-08 07:46
No, the mentioned PR didn't fix it. The issue is still present however I don't know how we could tackle it without reworking the transport completely.

**Closed** 2022-07-01 16:13 UTC
Labels: area: balance

**Comment by JaggedAppliance** [comment] 2022-08-26 18:08
Shouldn't this stay open? It's a valid issue.

**Comment by Garanas** [comment] 2022-08-29 08:22
We're changing how we look at issues. We'd like to have a list of issues that are:

- relevant to the current status quo of the game
- people can pick up and solve

This one doesn't meet either criteria: there is no direct interest / need from the balance team to push for a fix. And it isn't trivial either as Tagada states it requires an overhaul of the unit (mesh). 

With that idea we've been closing a lot of issues that are technically still an issue, but they are apparently not relevant enough to pick up. As an example of a few issues that are relevant and people can easily pick up and solve:

- https://github.com/FAForever/fa/issues/4134
- https://github.com/FAForever/fa/issues/4135
- https://github.com/FAForever/fa/issues/4136
