### ISSUE TITLE
Missing info box when selecting units with personal shield

### ISSUE THREAD

**Issue by ppipp** [FAForever/fa#805] opened 2015-07-21 20:22 UTC
In 3644, if you select a unit with personal shield like fatboy, various SCU presets, you cannot see the box where are displayed HP informations. Click on the unit, click eslewhere and click again to see the issue.

**Comment by quark036** [comment] 2015-07-21 20:24
duplicate of #801, I think

**Comment by shalkya** [comment] 2015-07-21 20:24
it's all unit that display shield. from structure, to mobile shield, personal shield unit....

**Comment by Sheeo** [comment] 2015-07-21 20:25
Yes duplicate of #801. Once this is fixed in develop we should get that remerged with the balance branch.

**Closed by Sheeo** 2015-07-21 20:25 UTC
Labels: duplicate
