### ISSUE TITLE
JsonStats not properly reported

### ISSUE THREAD

**Issue by micheljung** [FAForever/fa#1612] opened 2016-10-18 22:41 UTC
In pretty much all 4-5 games I recently played, the game never reported JsonStats. Those were all 4x4 games that took quite a while - so a lot of stats have to be sent.

My preliminary assumption is that either the string gets too big and the game somehow silently drops it, or that it's connected with "After-game graphs not displayed".

A healthy game looks like this:

```
INFO: creating high fidelity terrain
INFO: creating high fidelity water
INFO: GAMERESULT : \000defeat -10
INFO: GAMERESULT : \000victory 10
INFO: Sending stats: {"stats":[{"blueprints":{"ual0001":{"built":1,"lowest_health":11000},"uab5101":{"built":8},"uab1103":{"built":1}},"type":"Human","general":{"score":77,"currentcap":{"count":1000},"lastReclaimedMass":0,"mass":703.69287109375,"built":{"mass":52,"count":10,"energy":440},"kills":{"mass":0,"count":0,"energy":0},"lost":{"mass":0,"count":0,"energy":0},"currentunits":{"count":3.8000001907349},"energy":4696,"lastReclaimedEnergy":0},"faction":2,"resources":{"massin":{"total":703.69287109375,"rate":0.30000001192093},"energyout":{"total":993.60107421875,"rate":6.1999998092651},"energyin":{"total":4696,"rate":2},"energyover":308,"massover":9.8975830078125,"massout":{"total":105.79981231689,"rate":0.60000002384186}},"name":"Downlord","units":{"air":{"lost":0,"kills":0,"built":0},"tech3":{"lost":0,"kills":0,"built":0},"cdr":{"lost":0,"kills":0,"built":1},"tech2":{"lost":0,"kills":0,"built":0},"tech1":{"lost":0,"kills":0,"built":9},"transportation":{"lost":0,"kills":0,"built":0},"land":{"lost":0,"kills":0,"built":1},"sacu":{"lost":0,"kills":0,"built":0},"structures":{"lost":0,"kills":0,"built":9},"engineer":{"lost":0,"kills":0,"built":1},"naval":{"lost":0,"kills":0,"built":0},"experimental":{"lost":0,"kills":0,"built":0}}},{"blueprints":{"uel0001":{"lost":1,"built":1,"lowest_health":9500}},"type":"Human","general":{"score":85,"currentcap":{"count":1000},"lastReclaimedMass":0,"mass":671.09484863281,"built":{"mass":0,"count":1,"energy":0},"kills":{"mass":0,"count":0,"energy":0},"lost":{"mass":18000,"count":1,"energy":5000000},"currentunits":{"count":1},"energy":4422,"lastReclaimedEnergy":0},"faction":1,"resources":{"massin":{"total":671.09484863281,"rate":0},"energyout":{"total":1043,"rate":0},"energyin":{"total":4422,"rate":0},"energyover":3379,"massover":551.89666748047,"massout":{"total":119.20016479492,"rate":0}},"name":"Brutus5000","units":{"air":{"lost":0,"kills":0,"built":0},"tech3":{"lost":0,"kills":0,"built":0},"cdr":{"lost":1,"kills":0,"built":1},"tech2":{"lost":0,"kills":0,"built":0},"tech1":{"lost":0,"kills":0,"built":0},"transportation":{"lost":0,"kills":0,"built":0},"land":{"lost":1,"kills":0,"built":1},"sacu":{"lost":0,"kills":0,"built":0},"structures":{"lost":0,"kills":0,"built":0},"engineer":{"lost":1,"kills":0,"built":1},"naval":{"lost":0,"kills":0,"built":0},"experimental":{"lost":0,"kills":0,"built":0}}}]}
INFO: called Set_graph...
```

A broken game looks like so:
```
INFO: creating high fidelity terrain
INFO: creating high fidelity water
INFO: Hooked /lua/ui/game/scoreaccum.lua with /mods/supremeeconomy/hook/lua/ui/game/scoreaccum.lua
INFO: Hooked /lua/defaultantiprojectile.lua with /schook/lua/defaultantiprojectile.lua
INFO: Hooked /lua/ui/game/commandgraph.lua with /schook/lua/ui/game/commandgraph.lua
WARNING: ACU kill detected. Rating for ranked games is now enforced.
INFO: GAMERESULT : \000score 1
INFO: GAMERESULT : \000defeat -10
WARNING: ACU kill detected. Rating for ranked games is now enforced.
WARNING: ACU kill detected. Rating for ranked games is now enforced.
INFO: GAMERESULT : \000score 1
INFO: GAMERESULT : \000score 2
INFO: GAMERESULT : \000defeat -10
INFO: GAMERESULT : \000defeat -10
INFO: GAMERESULT : \000defeat -10
WARNING: ACU kill detected. Rating for ranked games is now enforced.
INFO: GAMERESULT : \000score 3
INFO: GAMERESULT : \000defeat -10
INFO: GAMERESULT : \000defeat -10
INFO: GAMERESULT : \000victory 10
INFO: GAMERESULT : \000victory 10
INFO: GAMERESULT : \000victory 10
INFO: GAMERESULT : \000victory 10
INFO: called Set_graph...
```
Good thing is, it's reproducible when watching the replay.

**Comment by aeoncleanse** [comment] 2016-10-18 23:11
I don't think it's getting too big. I've seen some game logs come in of successful games where the stats stuff was hundreds of lines long, so it would have to be an enormous game for that to be the case.

**Comment by micheljung** [comment] 2016-10-19 21:13
Could it be that stats are only sent by host? :\

**Comment by Exotic-Retard** [comment] 2016-10-19 21:34
just to make sure we are on the same page here - the broken game simply doesnt have the Sending stats:
line before called Set_graph ? right?

and its helpful if all the players send logs and not just one per game?

**Comment by Crotalus** [comment] 2016-10-20 03:08
An educated guess would be that this is caused by the 3s delay in `CallEndGame()` before actually stopping the sim. The score sync runs every `3s + <n_players>*0.1` so the risk is that the sim stops before a last sync with stats is sent.

The quick fix would be to force a manual `SyncScores()` right before WaitSeconds(3) in `CallEndGame()`.

Also, should rewrite the whole score / sync stuff really, I've noticed that it can cause some real performance degradation in longer games.

**Comment by Crotalus** [comment] 2016-10-20 06:08
Opened a pull request with the delay solution above.

**Comment by Crotalus** [comment] 2016-10-22 14:34
Fixed in 3660, so closing for now.

**Closed by Crotalus** 2016-10-22 14:34 UTC
Labels: bug, in progress

**Comment by micheljung** [comment] 2016-10-24 10:07
IMO we shouldn't manually close isse but have them automatically closed when merging into develop. Only the it's guaranteed that the fix made it into our code base.
